"""
title: ComfyUI SDXL Graph
author: Gordon
version: 1.1.0
description: Companion to ComfyUI SDXL Direct. Submits a full, model-authored ComfyUI API-format
    workflow graph (ControlNet, compositing, anything the fixed generate_image graph can't reach).
    Requires a SaveImage node so an image is guaranteed to land in the server's output folder, and
    always makes a fixed-id LoadImageOutput node available in the graph for optional image injection.
    Also lets a graph be saved as a named, reusable template (save_workflow/list_workflows/
    get_workflow/delete_workflow) in the shared job database, so run_workflow can be called again
    with workflow_id=<name> instead of resending the full graph JSON every time.
"""

import asyncio
import base64
import datetime
import json
import logging
import logging.handlers
import mimetypes
import re
import time
import urllib.parse
import uuid
from pathlib import Path
from typing import Any, Callable, Dict, List, Literal, Optional

import requests
from pydantic import BaseModel, Field
from requests.exceptions import RequestException

logger = logging.getLogger("comfy_sdxl_graph")
logger.setLevel(logging.INFO)

# The node id the tool reserves in every submitted graph for image injection.
# Deliberately not a plain number, so it won't collide with a model-authored graph.
SOURCE_IMAGE_NODE_ID = "__comfy_tool_source_image__"
PLACEHOLDER_FILENAME = "_comfy_tool_blank.png"
# The smallest valid PNG (1x1 transparent), used so the fixed LoadImageOutput node always
# points at a real file on the server, whether or not a given call actually uses it -
# ComfyUI's /prompt validation may check every submitted node, not just reachable ones.
_PLACEHOLDER_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
)

_placeholder_ready: set = set()  # server URLs confirmed (this process) to have the placeholder


# Everything below mirrors comfy_sdxl_direct.py / comfy_sdxl_retrieve.py. Open WebUI tools are
# single files, so shared logic is copied rather than imported; keep the three in sync by hand.

# --------------------------------------------------------------------------- #
# Job log (completed graph runs) - same scheme as generate_image's job log.
# --------------------------------------------------------------------------- #

_job_logger_cache: Dict[tuple, logging.Logger] = {}


def get_job_logger(v: Any) -> logging.Logger:
    key = (
        v.LOG_BACKEND, v.SYSLOG_ADDRESS, v.SYSLOG_IDENT,
        v.JOB_LOG_PATH, v.JOB_LOG_MAX_BYTES, v.JOB_LOG_BACKUP_COUNT,
    )
    cached = _job_logger_cache.get(key)
    if cached is not None:
        return cached

    job_logger = logging.getLogger(f"comfy_sdxl_graph.jobs.{abs(hash(key))}")
    job_logger.setLevel(logging.INFO)
    job_logger.propagate = False

    wired_syslog = False
    if v.LOG_BACKEND in ("syslog", "both"):
        try:
            handler = logging.handlers.SysLogHandler(address=v.SYSLOG_ADDRESS)
            handler.setFormatter(logging.Formatter(f"{v.SYSLOG_IDENT}: %(message)s"))
            job_logger.addHandler(handler)
            wired_syslog = True
        except OSError as e:
            logger.warning("Job log: could not open syslog socket %s: %s", v.SYSLOG_ADDRESS, e)

    if v.LOG_BACKEND in ("file", "both") or not wired_syslog:
        try:
            path = Path(v.JOB_LOG_PATH)
            path.parent.mkdir(parents=True, exist_ok=True)
            handler = logging.handlers.RotatingFileHandler(
                path, maxBytes=v.JOB_LOG_MAX_BYTES, backupCount=v.JOB_LOG_BACKUP_COUNT
            )
            handler.setFormatter(logging.Formatter("%(message)s"))
            job_logger.addHandler(handler)
        except OSError as e:
            logger.warning("Job log: could not open log file %s: %s", v.JOB_LOG_PATH, e)

    _job_logger_cache[key] = job_logger
    return job_logger


def log_completed_job(v: Any, record: Dict[str, Any]) -> None:
    if not v.LOG_JOBS:
        return
    try:
        line = json.dumps({"timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(), **record}, default=str)
        get_job_logger(v).info(line)
    except Exception as e:
        logger.warning("Job log: could not record completed job: %s", e)


# --------------------------------------------------------------------------- #
# SQLite job database - a queryable, verbatim record of every job attempt,
# alongside the syslog/file log above. Design:
#   - job_uuid is generated by the tool BEFORE any network call, so a job that
#     ComfyUI rejects or never responds to is still fully catalogued.
#   - jobs.comfy_prompt_id is filled in once/if the server assigns one, giving
#     a durable link between our id and the server's; it can stay NULL forever
#     for a job the server never saw. comfy_sdxl_retrieve.py's reconciliation
#     logic can backfill it later by matching the 'outputs' graph against a
#     history entry found by filename, for a job that appears server-side
#     without the tool having recorded the link itself.
#   - inputs/outputs/results/errors keep verbatim JSON; prompts and node_params
#     are the broken-out, queryable (non-JSON) columns.
# Shared schema with comfy_sdxl_direct.py and read/written by comfy_sdxl_retrieve.py;
# keep the three in sync by hand if this schema changes.
# --------------------------------------------------------------------------- #

JOB_DB_SCHEMA = """
CREATE TABLE IF NOT EXISTS jobs (
    job_uuid TEXT PRIMARY KEY,
    comfy_prompt_id TEXT,
    tool TEXT NOT NULL,
    server TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    submitted_at TEXT,
    execution_start_ts INTEGER,
    execution_end_ts INTEGER,
    duration_s REAL
);
CREATE INDEX IF NOT EXISTS idx_jobs_comfy_prompt_id ON jobs(comfy_prompt_id);
CREATE INDEX IF NOT EXISTS idx_jobs_server_status ON jobs(server, status);
CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON jobs(created_at);

CREATE TABLE IF NOT EXISTS inputs (
    job_uuid TEXT PRIMARY KEY REFERENCES jobs(job_uuid),
    raw_json TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS outputs (
    job_uuid TEXT PRIMARY KEY REFERENCES jobs(job_uuid),
    raw_json TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_uuid TEXT NOT NULL REFERENCES jobs(job_uuid),
    stage TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_results_job_uuid ON results(job_uuid);

CREATE TABLE IF NOT EXISTS errors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_uuid TEXT NOT NULL REFERENCES jobs(job_uuid),
    stage TEXT NOT NULL,
    message TEXT NOT NULL,
    raw_json TEXT,
    recorded_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_errors_job_uuid ON errors(job_uuid);

CREATE TABLE IF NOT EXISTS prompts (
    job_uuid TEXT PRIMARY KEY REFERENCES jobs(job_uuid),
    positive_prompt TEXT,
    negative_prompt TEXT
);

CREATE TABLE IF NOT EXISTS node_params (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_uuid TEXT NOT NULL REFERENCES jobs(job_uuid),
    node_id TEXT NOT NULL,
    class_type TEXT NOT NULL,
    param_name TEXT NOT NULL,
    value_text TEXT,
    value_num REAL
);
CREATE INDEX IF NOT EXISTS idx_node_params_job_uuid ON node_params(job_uuid);
CREATE INDEX IF NOT EXISTS idx_node_params_lookup ON node_params(class_type, param_name, value_text);
"""
PROMPTS_FTS_SCHEMA = "CREATE VIRTUAL TABLE IF NOT EXISTS prompts_fts USING fts5(job_uuid UNINDEXED, positive_prompt, negative_prompt);"

# Reusable named workflow graphs, keyed by a model-chosen slug (see "Workflow templates" section
# below). Same database file as the jobs tables, but a template is not a job - it has no job_uuid
# and isn't touched by the jobs/inputs/outputs/results/errors lifecycle above. This is the only one
# of the three tool files that reads/writes this table; it exists so a model can call
# run_workflow(workflow_id=...) instead of resending a full graph as JSON on every call.
WORKFLOW_TEMPLATES_SCHEMA = """
CREATE TABLE IF NOT EXISTS workflow_templates (
    name TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    graph_json TEXT NOT NULL,
    placeholders_json TEXT NOT NULL DEFAULT '{}',
    tags TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    created_by TEXT,
    version INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_workflow_templates_tags ON workflow_templates(tags);
"""

JOB_DB_BUSY_TIMEOUT_S = 5.0
_job_db_schema_ready: set = set()  # db_path values confirmed (this process) to have the schema


def job_db_connect(db_path: str):
    """A short-lived connection with the schema ensured. Caller must close() it."""
    import sqlite3

    Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path, timeout=JOB_DB_BUSY_TIMEOUT_S)
    conn.execute("PRAGMA journal_mode=WAL;")
    if db_path not in _job_db_schema_ready:
        conn.executescript(JOB_DB_SCHEMA)
        conn.executescript(WORKFLOW_TEMPLATES_SCHEMA)
        try:
            conn.execute(PROMPTS_FTS_SCHEMA)
        except Exception:  # sqlite3.OperationalError if this build lacks FTS5; search falls back to LIKE
            pass
        _job_db_schema_ready.add(db_path)
    return conn


def _now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def extract_node_params(graph: Dict[str, Any]) -> List[tuple]:
    """(node_id, class_type, param_name, value_text, value_num) for every scalar input in the
    graph. List-typed inputs are links to other nodes (e.g. ["12", 0]), not literal values, and
    are skipped - this only captures the literal parameters actually set on each node."""
    rows = []
    for node_id, node in graph.items():
        class_type = node.get("class_type", "")
        for name, value in (node.get("inputs") or {}).items():
            if isinstance(value, list):  # a link to another node's output, not a literal
                continue
            value_num = value if isinstance(value, (int, float)) and not isinstance(value, bool) else None
            rows.append((str(node_id), str(class_type), str(name), json.dumps(value) if not isinstance(value, str) else value, value_num))
    return rows


def has_prompts_fts(conn) -> bool:
    try:
        conn.execute("SELECT 1 FROM prompts_fts LIMIT 0;")
        return True
    except Exception:
        return False


def record_job_built(
    db_path: str,
    job_uuid: str,
    tool: str,
    server: str,
    input_json: Dict[str, Any],
    output_graph: Dict[str, Any],
    positive_prompt: Optional[str],
    negative_prompt: Optional[str],
) -> None:
    """
    First write for a job, made as soon as the graph is fully built - before it is ever sent
    to ComfyUI. This is what guarantees a job is catalogued even if the server rejects it or
    never responds at all.
    """
    try:
        conn = job_db_connect(db_path)
        try:
            now = _now_iso()
            conn.execute(
                "INSERT INTO jobs (job_uuid, tool, server, status, created_at) VALUES (?, ?, ?, 'built', ?)",
                (job_uuid, tool, server, now),
            )
            conn.execute(
                "INSERT INTO inputs (job_uuid, raw_json, recorded_at) VALUES (?, ?, ?)",
                (job_uuid, json.dumps(input_json, default=str), now),
            )
            conn.execute(
                "INSERT INTO outputs (job_uuid, raw_json, recorded_at) VALUES (?, ?, ?)",
                (job_uuid, json.dumps(output_graph, default=str), now),
            )
            conn.execute(
                "INSERT INTO prompts (job_uuid, positive_prompt, negative_prompt) VALUES (?, ?, ?)",
                (job_uuid, positive_prompt, negative_prompt),
            )
            if has_prompts_fts(conn):
                conn.execute(
                    "INSERT INTO prompts_fts (job_uuid, positive_prompt, negative_prompt) VALUES (?, ?, ?)",
                    (job_uuid, positive_prompt or "", negative_prompt or ""),
                )
            conn.executemany(
                "INSERT INTO node_params (job_uuid, node_id, class_type, param_name, value_text, value_num) VALUES (?, ?, ?, ?, ?, ?)",
                [(job_uuid, *row) for row in extract_node_params(output_graph)],
            )
            conn.commit()
        finally:
            conn.close()
    except Exception as e:
        logger.warning("Job DB: could not record built job %s: %s", job_uuid, e)


def record_job_submitted(db_path: str, job_uuid: str, comfy_prompt_id: str, submit_response: Dict[str, Any]) -> None:
    """Second write: the server accepted the job and assigned it a prompt_id."""
    try:
        conn = job_db_connect(db_path)
        try:
            now = _now_iso()
            conn.execute(
                "UPDATE jobs SET comfy_prompt_id = ?, status = 'queued', submitted_at = ? WHERE job_uuid = ?",
                (comfy_prompt_id, now, job_uuid),
            )
            conn.execute(
                "INSERT INTO results (job_uuid, stage, raw_json, recorded_at) VALUES (?, 'submit_response', ?, ?)",
                (job_uuid, json.dumps(submit_response, default=str), now),
            )
            conn.commit()
        finally:
            conn.close()
    except Exception as e:
        logger.warning("Job DB: could not record submitted job %s: %s", job_uuid, e)


def _execution_timing(history_entry: Dict[str, Any]) -> "tuple[Optional[int], Optional[int], Optional[float]]":
    """(start_ts_ms, end_ts_ms, duration_s), all None if the timestamps aren't present."""
    start_ts = end_ts = None
    for name, data in (history_entry.get("status") or {}).get("messages", []):
        ts = data.get("timestamp") if isinstance(data, dict) else None
        if name == "execution_start" and isinstance(ts, (int, float)):
            start_ts = int(ts)
        elif name in ("execution_success", "execution_error", "execution_interrupted") and isinstance(ts, (int, float)):
            end_ts = int(ts)
    duration = (end_ts - start_ts) / 1000 if start_ts is not None and end_ts is not None else None
    return start_ts, end_ts, duration


def record_job_completed(db_path: str, job_uuid: str, history_entry: Dict[str, Any]) -> None:
    """Final write on success: ComfyUI's history entry, with its own reported timing."""
    try:
        start_ts, end_ts, duration = _execution_timing(history_entry)
        conn = job_db_connect(db_path)
        try:
            now = _now_iso()
            conn.execute(
                "UPDATE jobs SET status = 'completed', execution_start_ts = ?, execution_end_ts = ?, duration_s = ? WHERE job_uuid = ?",
                (start_ts, end_ts, duration, job_uuid),
            )
            conn.execute(
                "INSERT INTO results (job_uuid, stage, raw_json, recorded_at) VALUES (?, 'history', ?, ?)",
                (job_uuid, json.dumps(history_entry, default=str), now),
            )
            conn.commit()
        finally:
            conn.close()
    except Exception as e:
        logger.warning("Job DB: could not record completed job %s: %s", job_uuid, e)


def record_job_failed(db_path: str, job_uuid: str, stage: str, message: str, raw_json: Optional[Dict[str, Any]] = None) -> None:
    """
    Final write on failure: rejected by the server (stage='submit'), or accepted but never
    finished (stage='wait' - timeout, lost connection, or an execution_error from the server).
    """
    status = "rejected" if stage == "submit" else "failed"
    try:
        conn = job_db_connect(db_path)
        try:
            now = _now_iso()
            conn.execute("UPDATE jobs SET status = ? WHERE job_uuid = ?", (status, job_uuid))
            conn.execute(
                "INSERT INTO errors (job_uuid, stage, message, raw_json, recorded_at) VALUES (?, ?, ?, ?, ?)",
                (job_uuid, stage, message, json.dumps(raw_json, default=str) if raw_json is not None else None, now),
            )
            conn.commit()
        finally:
            conn.close()
    except Exception as e:
        logger.warning("Job DB: could not record failed job %s: %s", job_uuid, e)


# --------------------------------------------------------------------------- #
# Workflow templates - save a model-authored graph once, reuse it by name.
# Unlike the jobs tables above, a template is mutable (overwrite bumps `version`
# in place) rather than an append-only log: past jobs that used it already have
# their exact submitted graph preserved verbatim in `outputs`, so nothing about
# provenance depends on keeping old template revisions around too.
# --------------------------------------------------------------------------- #

def save_workflow_template(
    db_path: str,
    name: str,
    description: str,
    graph: Dict[str, Any],
    placeholders: Dict[str, List[str]],
    tags: str,
    created_by: str,
) -> int:
    """Insert or overwrite a template by name. Returns the resulting version number."""
    conn = job_db_connect(db_path)
    try:
        now = _now_iso()
        row = conn.execute("SELECT version, created_at FROM workflow_templates WHERE name = ?", (name,)).fetchone()
        version = (row[0] + 1) if row else 1
        created_at = row[1] if row else now
        conn.execute(
            "INSERT INTO workflow_templates "
            "(name, description, graph_json, placeholders_json, tags, created_at, updated_at, created_by, version) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(name) DO UPDATE SET description=excluded.description, graph_json=excluded.graph_json, "
            "placeholders_json=excluded.placeholders_json, tags=excluded.tags, updated_at=excluded.updated_at, "
            "created_by=excluded.created_by, version=excluded.version",
            (
                name, description, json.dumps(graph, default=str), json.dumps(placeholders, default=str),
                tags, created_at, now, created_by, version,
            ),
        )
        conn.commit()
        return version
    finally:
        conn.close()


def load_workflow_template(db_path: str, name: str) -> Optional[Any]:
    import sqlite3

    conn = job_db_connect(db_path)
    try:
        conn.row_factory = sqlite3.Row
        return conn.execute("SELECT * FROM workflow_templates WHERE name = ?", (name,)).fetchone()
    finally:
        conn.close()


def list_workflow_templates(db_path: str, tag: Optional[str] = None, search: Optional[str] = None, limit: int = 20) -> List[Any]:
    import sqlite3

    conn = job_db_connect(db_path)
    try:
        conn.row_factory = sqlite3.Row
        query = "SELECT name, description, tags, version, updated_at FROM workflow_templates WHERE 1=1"
        params: List[Any] = []
        if not is_unset(tag):
            query += " AND (',' || tags || ',') LIKE ? ESCAPE '\\'"
            params.append(f"%,{_like_escape(tag.strip().lower())},%")
        if not is_unset(search):
            query += " AND (name LIKE ? ESCAPE '\\' OR description LIKE ? ESCAPE '\\')"
            like = f"%{_like_escape(search)}%"
            params += [like, like]
        query += " ORDER BY updated_at DESC LIMIT ?"
        params.append(max(1, int(limit)))
        return conn.execute(query, params).fetchall()
    finally:
        conn.close()


def delete_workflow_template(db_path: str, name: str) -> bool:
    conn = job_db_connect(db_path)
    try:
        cur = conn.execute("DELETE FROM workflow_templates WHERE name = ?", (name,))
        conn.commit()
        return cur.rowcount > 0
    finally:
        conn.close()


# --------------------------------------------------------------------------- #
# Small pure helpers
# --------------------------------------------------------------------------- #

_UNSET_STRINGS = {"", "default", "auto", "none", "null", "undefined", "n/a"}
_ANNOTATION_RE = re.compile(r"\s*\[(\w+)\]\s*$")
_CKPT_LOADER_CLASSES = ("CheckpointLoaderSimple", "CheckpointLoader", "unCLIPCheckpointLoader")
_CKPT_EXT_RE = re.compile(r"\.(safetensors|ckpt|pt|pth|bin|sft)$", re.I)
_TEMPLATE_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{1,63}$")


def is_unset(value: Any) -> bool:
    return value is None or (isinstance(value, str) and value.strip().lower() in _UNSET_STRINGS)


def _like_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")


def _truncate(text: str, limit: int) -> str:
    text = text or ""
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "\N{HORIZONTAL ELLIPSIS}"


def validate_template_name(name: str) -> str:
    normalized = (name or "").strip().lower()
    if not _TEMPLATE_NAME_RE.match(normalized):
        raise ValueError(
            f"Invalid workflow template name {name!r}: use 2-64 lowercase letters, digits, "
            "underscores or hyphens, starting with a letter or digit."
        )
    return normalized


def validate_placeholders(graph: Dict[str, Any], placeholders: Dict[str, Any]) -> Dict[str, List[str]]:
    """
    placeholders: {param_name: [node_id, input_name]}. Every entry must point at a literal
    (non-link) input that actually exists in this graph - the same shape apply_overrides() later
    relies on to safely mutate a copy of the stored graph. Returns a normalized copy (string ids).
    """
    normalized: Dict[str, List[str]] = {}
    for param_name, loc in placeholders.items():
        if not (isinstance(loc, (list, tuple)) and len(loc) == 2):
            raise ValueError(f"placeholders[{param_name!r}] must be a [node_id, input_name] pair.")
        node_id, input_name = str(loc[0]), str(loc[1])
        node = graph.get(node_id)
        if node is None:
            raise ValueError(f"placeholders[{param_name!r}] refers to node {node_id!r}, which isn't in this graph.")
        inputs = node.get("inputs") or {}
        if input_name not in inputs:
            raise ValueError(f"placeholders[{param_name!r}] refers to input {input_name!r} on node {node_id!r}, which has no such input.")
        if isinstance(inputs[input_name], list):
            raise ValueError(f"placeholders[{param_name!r}] points at {node_id}.{input_name}, which is wired to another node's output, not a literal value.")
        normalized[str(param_name)] = [node_id, input_name]
    return normalized


def apply_overrides(graph: Dict[str, Any], placeholders: Dict[str, List[str]], overrides: Dict[str, Any]) -> None:
    """Mutates graph in place, setting each override's literal value at its registered placeholder."""
    unknown = [k for k in overrides if k not in placeholders]
    if unknown:
        available = sorted(placeholders.keys()) or ["(this template has no overridable parameters)"]
        raise ValueError(f"Unknown override(s) {unknown} for this template; available parameters are: {available}.")
    for param_name, value in overrides.items():
        node_id, input_name = placeholders[param_name]
        node = graph.get(node_id)
        if node is None or input_name not in (node.get("inputs") or {}):
            raise ValueError(
                f"Stored placeholder for {param_name!r} ({node_id}.{input_name}) no longer matches this "
                "template's graph; re-save it with save_workflow."
            )
        node["inputs"][input_name] = value


def resolve_server(
    requested: Optional[str], default: str, allowed: List[str], allow_unlisted: bool = False
) -> str:
    allowed_norm = [s.rstrip("/") for s in allowed]
    if is_unset(requested):
        return default.rstrip("/")

    wanted = requested.strip()
    if wanted.endswith("/") and not wanted.endswith("://"):
        wanted = wanted[:-1]
    if wanted in allowed_norm:
        return wanted

    with_scheme = wanted if "://" in wanted else f"http://{wanted}"
    parsed = urllib.parse.urlparse(with_scheme)
    for server in allowed_norm:
        s = urllib.parse.urlparse(server)
        if parsed.hostname == s.hostname and (parsed.port is None or parsed.port == s.port):
            return server

    if allow_unlisted:
        if parsed.scheme not in ("http", "https") or not parsed.hostname:
            raise ValueError(f"gpu_server {requested!r} is not a valid http(s) address.")
        try:
            port = parsed.port
        except ValueError:
            raise ValueError(f"gpu_server {requested!r} has an invalid port.") from None
        host = f"[{parsed.hostname}]" if ":" in parsed.hostname else parsed.hostname
        return f"{parsed.scheme}://{host}:{port or 8188}"

    raise ValueError(
        f"Unknown gpu_server {requested!r}. Omit it to use the default, choose one of {allowed_norm}, "
        "or enable the ALLOW_UNLISTED_SERVERS valve."
    )


def parse_source_image(ref: str) -> "tuple[str, str]":
    text = (ref or "").strip()
    md = re.search(r"\((https?://[^)\s]+)\)", text)
    if md:
        text = md.group(1)
    if text.startswith(("http://", "https://")):
        query = urllib.parse.parse_qs(urllib.parse.urlparse(text).query)
        filename = (query.get("filename") or [""])[0]
        if not filename:
            raise ValueError("source_image URL has no 'filename' parameter.")
        if (query.get("type") or ["output"])[0] != "output":
            raise ValueError("source_image must be in the ComfyUI output folder.")
        subfolder = (query.get("subfolder") or [""])[0]
        text = f"{subfolder}/{filename}" if subfolder else filename
    annotation = _ANNOTATION_RE.search(text)
    if annotation:
        if annotation.group(1) != "output":
            raise ValueError("source_image must be in the ComfyUI output folder.")
        text = text[: annotation.start()]
    text = text.replace("\\", "/").strip("/")
    parts = text.split("/")
    if not text or ".." in parts:
        raise ValueError(f"Invalid source_image: {ref!r}")
    return "/".join(parts[:-1]), parts[-1]


def normalize_source_image(ref: str) -> str:
    subfolder, filename = parse_source_image(ref)
    return f"{subfolder}/{filename} [output]" if subfolder else f"{filename} [output]"


def _ckpt_basename(name: str) -> str:
    return name.replace("\\", "/").rsplit("/", 1)[-1]


def _ckpt_key(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "", _CKPT_EXT_RE.sub("", _ckpt_basename(name)).lower())


def resolve_checkpoint(requested: str, available: List[str]) -> str:
    """Same matching generate_image uses: exact, case/slash-insensitive, same basename, unique fuzzy match."""
    if requested in available:
        return requested
    norm = requested.replace("\\", "/").strip().lower()
    for a in available:
        if a.replace("\\", "/").lower() == norm:
            return a
    base = _ckpt_basename(requested).strip().lower()
    same_base = [a for a in available if _ckpt_basename(a).lower() == base]
    if len(same_base) == 1:
        return same_base[0]
    key = _ckpt_key(requested)
    fuzzy = [a for a in available if key and key in _ckpt_key(a)]
    if not same_base and len(fuzzy) == 1:
        return fuzzy[0]
    ambiguous = same_base or fuzzy
    if ambiguous:
        raise ValueError(f"Checkpoint {requested!r} is ambiguous on this server; could be any of: {sorted(ambiguous)}.")
    shown = sorted(available)[:80]
    more = f" (+{len(available) - 80} more)" if len(available) > 80 else ""
    raise ValueError(f"Checkpoint {requested!r} was not found on this server. Available: {shown}{more}.")


def format_execution_error(status: Dict[str, Any]) -> str:
    for name, data in status.get("messages", []):
        if name == "execution_error":
            return f"{data.get('node_type', 'node')} {data.get('node_id', '?')}: {data.get('exception_message', 'execution failed')}".strip()
    return "ComfyUI reported an execution error."


def _format_prompt_error(body: Dict[str, Any]) -> str:
    parts = []
    err = body.get("error")
    if isinstance(err, dict):
        parts.append(err.get("message") or err.get("type") or "prompt rejected")
        if err.get("details"):
            parts.append(str(err["details"]))
    elif err:
        parts.append(str(err))
    for node_id, info in (body.get("node_errors") or {}).items():
        for e in info.get("errors", []):
            parts.append(f"node {node_id} ({info.get('class_type', '?')}): {e.get('message', '')} {e.get('details', '')}".strip())
    return "; ".join(p for p in parts if p) or "ComfyUI rejected the prompt."


# --------------------------------------------------------------------------- #
# Graph validation / preparation
# --------------------------------------------------------------------------- #

def extract_prompts(graph: Dict[str, Any]) -> "tuple[Optional[str], Optional[str]]":
    """
    Best-effort positive/negative prompt text for the job database's prompts table (so custom
    graphs are searchable the same way generate_image's are). Only follows the common KSampler
    -> CLIPTextEncode wiring; returns (None, None) for anything else rather than guessing.
    """
    sampler = next((n for n in graph.values() if n.get("class_type") in ("KSampler", "KSamplerAdvanced")), None)
    if not sampler:
        return None, None

    def _text(link: Any) -> Optional[str]:
        if isinstance(link, list) and len(link) == 2:
            target = graph.get(str(link[0])) or {}
            text = (target.get("inputs") or {}).get("text")
            return text if isinstance(text, str) else None
        return None

    inputs = sampler.get("inputs") or {}
    return _text(inputs.get("positive")), _text(inputs.get("negative"))


def parse_workflow(workflow: Any) -> Dict[str, Any]:
    """Accept a JSON string or a dict; return the graph as a dict of node_id -> node."""
    if isinstance(workflow, str):
        try:
            graph = json.loads(workflow)
        except ValueError as e:
            raise ValueError(f"workflow is not valid JSON: {e}") from e
    else:
        graph = workflow
    if not isinstance(graph, dict) or not graph:
        raise ValueError("workflow must be a non-empty JSON object of node_id -> {class_type, inputs}, ComfyUI's API/export format.")
    for node_id, node in graph.items():
        if not isinstance(node, dict) or "class_type" not in node:
            raise ValueError(f"Node {node_id!r} is missing 'class_type'. Every node needs {{'class_type': ..., 'inputs': {{...}}}}.")
        node.setdefault("inputs", {})
    return graph


def validate_graph_shape(graph: Dict[str, Any]) -> None:
    """The two structural checks every graph needs, whether it's about to be submitted
    (prepare_graph) or saved as a template (save_workflow) for later reuse."""
    if SOURCE_IMAGE_NODE_ID in graph:
        raise ValueError(
            f"Node id {SOURCE_IMAGE_NODE_ID!r} is reserved by this tool for the fixed source-image "
            "node; use a different id for your own nodes."
        )
    if not any(n.get("class_type") == "SaveImage" for n in graph.values()):
        raise ValueError(
            "The graph has no SaveImage node, so nothing would land in the server's output folder. "
            "Add a SaveImage node fed from your final IMAGE output."
        )


def prepare_graph(
    graph: Dict[str, Any], filename_prefix: str, source_image_ref: Optional[str]
) -> "tuple[Dict[str, Any], bool]":
    """
    Validate the graph and inject the fixed source-image node. Returns (graph, needs_placeholder).
    Raises ValueError for anything the model needs to fix before submission.
    """
    validate_graph_shape(graph)
    save_nodes = [n for n in graph.values() if n.get("class_type") == "SaveImage"]
    for node in save_nodes:
        node["inputs"].setdefault("filename_prefix", filename_prefix)

    needs_placeholder = is_unset(source_image_ref)
    annotated = f"{PLACEHOLDER_FILENAME} [output]" if needs_placeholder else normalize_source_image(source_image_ref)
    graph[SOURCE_IMAGE_NODE_ID] = {"class_type": "LoadImageOutput", "inputs": {"image": annotated}}
    return graph, needs_placeholder


# --------------------------------------------------------------------------- #
# ComfyUI I/O
# --------------------------------------------------------------------------- #

class ComfyError(Exception):
    def __init__(self, message: str, body: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.body = body


NODE_TYPE_LABELS = {  # a few common ones get friendlier phrasing; anything else uses its class_type verbatim
    "CheckpointLoaderSimple": "Loading checkpoint",
    "ControlNetLoader": "Loading ControlNet",
    "ControlNetApply": "Applying ControlNet",
    "ControlNetApplyAdvanced": "Applying ControlNet",
    "VAEDecode": "Decoding image",
    "VAEEncode": "Encoding image",
    "SaveImage": "Saving image",
    "LoadImageOutput": "Loading image",
    "LoadImage": "Loading image",
}
PROGRESS_MIN_INTERVAL_SECONDS = 0.3
WS_CONNECT_WAIT_SECONDS = 2.0
POLL_INTERVAL_SECONDS = 1.0


def progress_message(
    event: Dict[str, Any],
    state: Dict[str, Any],
    node_labels: Dict[str, str],
    prompt_id: Optional[str] = None,
    now: Optional[float] = None,
) -> Optional[str]:
    etype = event.get("type")
    data = event.get("data") or {}
    pid = data.get("prompt_id")
    if pid and prompt_id and pid != prompt_id:
        return None

    if etype == "status":
        remaining = ((data.get("status") or {}).get("exec_info") or {}).get("queue_remaining")
        if isinstance(remaining, int) and remaining > 1 and not state.get("started"):
            return f"Queued: {remaining - 1} job(s) ahead of this one"
        return None

    if etype == "execution_start":
        state["started"] = True
        return "Starting..."

    if etype == "executing":
        node = data.get("node")
        if node is None:
            return None
        state["started"] = True
        state["node"] = str(node)
        return f"{node_labels.get(str(node), 'Working')}..."

    if etype == "progress":
        value, maximum = data.get("value"), data.get("max")
        if not (isinstance(value, int) and isinstance(maximum, int) and maximum > 0):
            return None
        state["started"] = True
        t = time.monotonic() if now is None else now
        if value < maximum and t - state.get("last_progress", float("-inf")) < PROGRESS_MIN_INTERVAL_SECONDS:
            return None
        state["last_progress"] = t
        node = str(data.get("node") or state.get("node") or "")
        return f"{node_labels.get(node, 'Working')}: step {value}/{maximum} ({round(100 * value / maximum)}%)"

    return None


class ComfyClient:
    def __init__(self, base_url: str, timeout: int):
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    def submit_prompt(self, workflow: Dict[str, Any], client_id: str) -> Dict[str, Any]:
        try:
            r = requests.post(f"{self.base_url}/prompt", json={"prompt": workflow, "client_id": client_id}, timeout=self.timeout)
        except RequestException as e:
            raise ComfyError(f"Cannot reach ComfyUI at {self.base_url}: {e}") from e
        if r.status_code != 200:
            try:
                body = r.json()
            except ValueError:
                body = {"error": r.text[:500]}
            raise ComfyError(_format_prompt_error(body), body=body)
        return r.json()

    def get_history(self, job_id: str) -> Optional[Dict[str, Any]]:
        try:
            r = requests.get(f"{self.base_url}/history/{job_id}", timeout=self.timeout)
            r.raise_for_status()
            return r.json().get(job_id)
        except RequestException as e:
            raise ComfyError(f"Lost contact with ComfyUI while waiting: {e}") from e

    def get_queue(self) -> Dict[str, Any]:
        try:
            r = requests.get(f"{self.base_url}/queue", timeout=self.timeout)
            r.raise_for_status()
            data = r.json()
        except (RequestException, ValueError) as e:
            raise ComfyError(f"Cannot read the queue from {self.base_url}: {e}") from e
        return data if isinstance(data, dict) else {}

    def jobs_ahead(self, number: Any) -> Optional[int]:
        if not isinstance(number, int):
            return None
        try:
            q = self.get_queue()
            items = list(q.get("queue_running", [])) + list(q.get("queue_pending", []))
            return sum(1 for it in items if isinstance(it, (list, tuple)) and it and isinstance(it[0], int) and it[0] < number)
        except (ComfyError, AttributeError, TypeError):
            return None

    def list_checkpoints(self) -> List[str]:
        try:
            r = requests.get(f"{self.base_url}/object_info/CheckpointLoaderSimple", timeout=self.timeout)
            r.raise_for_status()
            spec = r.json()["CheckpointLoaderSimple"]["input"]["required"]["ckpt_name"]
            if isinstance(spec[0], list):
                return [str(x) for x in spec[0]]
            if spec[0] == "COMBO" and len(spec) > 1:
                return [str(x) for x in spec[1].get("options", [])]
        except (RequestException, KeyError, IndexError, TypeError, ValueError) as e:
            logger.warning("Could not list checkpoints on %s: %s", self.base_url, e)
        return []

    def view_url(self, image: Dict[str, Any]) -> str:
        query = urllib.parse.urlencode({"filename": image["filename"], "subfolder": image.get("subfolder", ""), "type": image.get("type", "output")})
        return f"{self.base_url}/view?{query}"

    def fetch_image(self, image: Dict[str, Any]) -> Optional[bytes]:
        try:
            r = requests.get(self.view_url(image), timeout=self.timeout)
        except RequestException as e:
            raise ComfyError(f"Could not download {image['filename']}: {e}") from e
        if r.status_code == 404:
            return None
        if r.status_code != 200:
            raise ComfyError(f"{self.base_url} answered HTTP {r.status_code} for {image['filename']}")
        return r.content

    def upload_image(self, image_bytes: bytes, filename: str, subfolder: str = "", type_: str = "output") -> Dict[str, str]:
        try:
            r = requests.post(
                f"{self.base_url}/upload/image",
                files={"image": (filename, image_bytes, mimetypes.guess_type(filename)[0] or "image/png")},
                data={"subfolder": subfolder, "type": type_, "overwrite": "true"},
                timeout=self.timeout,
            )
            r.raise_for_status()
            data = r.json()
        except RequestException as e:
            raise ComfyError(f"Could not upload {filename} to {self.base_url}: {e}") from e
        except ValueError as e:
            raise ComfyError(f"Unexpected upload response from {self.base_url}: {e}") from e
        return {"filename": data.get("name", filename), "subfolder": data.get("subfolder", subfolder), "type": data.get("type", type_)}

    async def _listen_progress(
        self,
        client_id: str,
        prompt_box: Dict[str, Optional[str]],
        node_labels: Dict[str, str],
        on_status: Callable[[str], Any],
        connected: asyncio.Event,
    ) -> None:
        try:
            import aiohttp
        except ImportError:
            connected.set()
            return
        ws_url = f"{self.base_url.replace('http', 'ws', 1)}/ws?clientId={client_id}"
        state: Dict[str, Any] = {}
        try:
            timeout = aiohttp.ClientTimeout(total=None, sock_connect=self.timeout)
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.ws_connect(ws_url, max_msg_size=16 * 1024 * 1024) as ws:
                    connected.set()
                    async for msg in ws:
                        if msg.type in (aiohttp.WSMsgType.CLOSED, aiohttp.WSMsgType.ERROR):
                            break
                        if msg.type != aiohttp.WSMsgType.TEXT:
                            continue
                        try:
                            event = json.loads(msg.data)
                        except ValueError:
                            continue
                        text = progress_message(event, state, node_labels, prompt_box.get("id"))
                        if text:
                            await on_status(text)
        except asyncio.CancelledError:
            raise
        except Exception as e:
            logger.debug("Progress websocket unavailable on %s: %s", self.base_url, e)
        finally:
            connected.set()

    async def run(
        self,
        workflow: Dict[str, Any],
        max_wait: int,
        node_labels: Dict[str, str],
        on_status: Optional[Callable[[str], Any]] = None,
        show_progress: bool = True,
        job_uuid: Optional[str] = None,
        db_path: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Queue the workflow and wait for it. If job_uuid and db_path are given, records every
        stage (submitted, completed, or failed/rejected at the correct stage) as it happens.
        """
        client_id = str(uuid.uuid4())
        prompt_box: Dict[str, Optional[str]] = {"id": None}
        listener = None
        if on_status and show_progress:
            connected = asyncio.Event()
            listener = asyncio.create_task(self._listen_progress(client_id, prompt_box, node_labels, on_status, connected))
            try:
                await asyncio.wait_for(connected.wait(), timeout=WS_CONNECT_WAIT_SECONDS)
            except asyncio.TimeoutError:
                pass
        try:
            try:
                info = await asyncio.to_thread(self.submit_prompt, workflow, client_id)
            except ComfyError as e:
                if job_uuid and db_path:
                    await asyncio.to_thread(record_job_failed, db_path, job_uuid, "submit", str(e), e.body)
                raise
            prompt_id = info["prompt_id"]
            prompt_box["id"] = prompt_id
            if on_status:
                await on_status(f"Queued on {self.base_url} (prompt {prompt_id[:8]})...")
            if job_uuid and db_path:
                await asyncio.to_thread(record_job_submitted, db_path, job_uuid, prompt_id, info)

            try:
                deadline = time.monotonic() + max_wait
                while True:
                    entry = await asyncio.to_thread(self.get_history, prompt_id)
                    if entry:
                        status = entry.get("status", {})
                        if status.get("status_str") == "error":
                            raise ComfyError(format_execution_error(status))
                        if status.get("completed") or entry.get("outputs"):
                            break
                    if time.monotonic() > deadline:
                        raise ComfyError(f"Timed out after {max_wait}s (prompt {prompt_id} may still be running on the server).")
                    await asyncio.sleep(POLL_INTERVAL_SECONDS)
            except ComfyError as e:
                if job_uuid and db_path:
                    await asyncio.to_thread(record_job_failed, db_path, job_uuid, "wait", str(e))
                raise
        finally:
            if listener:
                listener.cancel()
                await asyncio.gather(listener, return_exceptions=True)

        images = [
            img
            for out in (entry.get("outputs") or {}).values()
            for img in (out.get("images") or [])
            if img.get("type", "output") == "output"
        ]
        if not images:
            msg = "Workflow finished but produced no images (check that your SaveImage node is actually fed by the final image)."
            if job_uuid and db_path:
                await asyncio.to_thread(record_job_failed, db_path, job_uuid, "wait", msg)
            raise ComfyError(msg)
        if job_uuid and db_path:
            await asyncio.to_thread(record_job_completed, db_path, job_uuid, entry)
        return {"prompt_id": prompt_id, "images": images, "history": entry}


async def ensure_placeholder(client: "ComfyClient", timeout: int) -> None:
    """Make sure the tiny placeholder PNG exists on this server's output folder. Cached per-process."""
    if client.base_url in _placeholder_ready:
        return
    existing = await asyncio.to_thread(client.fetch_image, {"filename": PLACEHOLDER_FILENAME, "subfolder": "", "type": "output"})
    if existing is None:
        await asyncio.to_thread(client.upload_image, base64.b64decode(_PLACEHOLDER_PNG_B64), PLACEHOLDER_FILENAME, "", "output")
    _placeholder_ready.add(client.base_url)


async def copy_source_image(source_server: str, target_client: "ComfyClient", subfolder: str, filename: str, timeout: int) -> None:
    src = ComfyClient(source_server, timeout)
    data = await asyncio.to_thread(src.fetch_image, {"filename": filename, "subfolder": subfolder, "type": "output"})
    if data is None:
        raise ComfyError(f"{filename!r} was not found in {source_server}'s output folder.")
    await asyncio.to_thread(target_client.upload_image, data, filename, subfolder, "output")


def upload_to_open_webui(base_url: str, api_key: str, image_bytes: bytes, filename: str, timeout: int) -> "tuple[Optional[str], Optional[str]]":
    if not api_key:
        return None, "OPEN_WEBUI_API_KEY is empty in the tool's valves"
    try:
        resp = requests.post(
            f"{base_url.rstrip('/')}/api/v1/files/",
            headers={"Authorization": f"Bearer {api_key}"},
            files={"file": (filename, image_bytes, mimetypes.guess_type(filename)[0] or "image/png")},
            params={"process": "false"},
            timeout=timeout,
        )
        resp.raise_for_status()
        file_id = resp.json().get("id")
        if not file_id:
            return None, f"upload response had no 'id' field: {str(resp.text)[:200]}"
        return f"/api/v1/files/{file_id}/content", None
    except RequestException as e:
        detail = ""
        response = getattr(e, "response", None)
        if response is not None:
            detail = f" (HTTP {response.status_code}: {str(response.text)[:200]})"
        return None, f"{e}{detail}"
    except ValueError as e:
        return None, f"unexpected response from Open WebUI: {e}"


async def _emit(emitter: Optional[Callable], payload: Dict[str, Any]) -> None:
    if emitter:
        await emitter(payload)


# --------------------------------------------------------------------------- #
# Open WebUI tool
# --------------------------------------------------------------------------- #

class Tools:
    class Valves(BaseModel):
        GPU_SERVERS: List[str] = Field(default=["http://192.168.10.11:8188", "http://192.168.10.12:8188"], description="ComfyUI servers, same list as the other two tools.")
        DEFAULT_GPU_SERVER: str = Field(default="http://192.168.10.11:8188", description="Server used when the model doesn't pick one.")
        ALLOW_UNLISTED_SERVERS: bool = Field(default=True, description="Let the model target any well-formed ComfyUI address, not just the ones in GPU_SERVERS.")
        FILENAME_PREFIX: str = Field(default="sdxl_graph", description="Default SaveImage filename_prefix used for any SaveImage node that doesn't set its own.")
        OUTPUT_DIR: str = Field(default="/app/backend/data/comfy_outputs", description="Where local copies are written when SAVE_LOCAL_COPY is on.")
        SAVE_LOCAL_COPY: bool = Field(default=False, description="Also keep a copy of each result in OUTPUT_DIR.")
        UPLOAD_TO_OPEN_WEBUI: bool = Field(default=True, description="Upload results into Open WebUI's own file storage. Needs OPEN_WEBUI_API_KEY.")
        OPEN_WEBUI_BASE_URL: str = Field(default="http://localhost:8080", description="Address the tool uses to call Open WebUI's own API, from the backend's point of view.")
        OPEN_WEBUI_API_KEY: str = Field(default="", description="Personal API key from Open WebUI (Settings -> Account -> API Keys).")
        MAX_WAIT_SECONDS: int = Field(default=300, description="Give up on a render after this long.")
        REQUEST_TIMEOUT_SECONDS: int = Field(default=15, description="Per-HTTP-request timeout.")
        SHOW_PROGRESS: bool = Field(default=True, description="Show live progress in Open WebUI's status line, via ComfyUI's websocket. Labels use each node's raw class_type, since a custom graph has no fixed node numbers to name.")
        IMAGE_DELIVERY: Literal["model_embed", "files_event", "message_event"] = Field(
            default="model_embed",
            description="How the finished image reaches the chat, same three modes as generate_image: 'model_embed' (default), 'files_event', or 'message_event'.",
        )
        LOG_JOBS: bool = Field(
            default=True,
            description="Keep a durable record of every completed run (the submitted graph, timestamp, filenames, server) for later reference. Not applied to queue_only submissions.",
        )
        LOG_BACKEND: Literal["syslog", "file", "both"] = Field(
            default="both",
            description="'syslog' writes to the local syslog socket (journald picks it up as 'journalctl -t <SYSLOG_IDENT>' IF this process's /dev/log is the host's journald socket - not true by default in an unmodified Docker container). 'file' writes a rotating JSON-lines file at JOB_LOG_PATH. 'both' tries syslog and always keeps the file too, so a job is never lost if syslog isn't reachable.",
        )
        SYSLOG_ADDRESS: str = Field(
            default="/dev/log",
            description="Syslog socket path. In Docker, only reaches the host's journal if /dev/log is bind-mounted in; otherwise entries land in the container's own log stream instead.",
        )
        SYSLOG_IDENT: str = Field(
            default="comfy_sdxl_graph",
            description="Syslog program identifier to filter by, e.g. `journalctl -t comfy_sdxl_graph` or `docker logs <container> | grep comfy_sdxl_graph`.",
        )
        JOB_LOG_PATH: str = Field(
            default="/app/backend/data/comfy_outputs/graph_job_log.jsonl",
            description="Rotating JSON-lines file of completed graph runs (one job per line, including the full submitted workflow). Used when LOG_BACKEND is 'file' or 'both', and automatically as a fallback if the syslog socket can't be opened.",
        )
        JOB_LOG_MAX_BYTES: int = Field(default=5_000_000, description="Rotate the job log file after it reaches this size.")
        JOB_LOG_BACKUP_COUNT: int = Field(default=5, description="How many rotated job log files to keep.")
        LOG_TO_SQLITE: bool = Field(
            default=True,
            description="Record every job attempt into the same queryable SQLite database generate_image uses (searchable via retrieve_image's search_jobs) - including rejected or timed-out jobs, not just completed renders. Independent of LOG_JOBS/LOG_BACKEND, which are the separate syslog/file log of completed renders only.",
        )
        JOB_DB_PATH: str = Field(
            default="/app/backend/data/comfy_outputs/comfy_jobs.sqlite3",
            description="SQLite database file for the job index. Keep this identical to generate_image's and retrieve_image's JOB_DB_PATH valve so all three tools share one database.",
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    async def save_workflow(
        self,
        name: str,
        workflow: str,
        description: str,
        placeholders: Optional[str] = None,
        tags: Optional[str] = None,
        overwrite: bool = False,
    ) -> Dict[str, Any]:
        """
        Save a ComfyUI workflow graph as a named, reusable template in the shared job database -
        not in this chat's context. Once saved, run_workflow(workflow_id=<name>, ...) renders with
        it without ever resending the graph JSON again. Save AFTER a run_workflow(workflow=...)
        call has actually rendered successfully with this exact graph - don't save something
        untested.

        :param name: A short slug (2-64 chars: lowercase letters, digits, underscore, hyphen), e.g. "controlnet_openpose_sdxl". This becomes run_workflow's workflow_id.
        :param workflow: The ComfyUI API-format graph as a JSON string - the same shape run_workflow's own `workflow` argument takes (no reserved source-image node; that's injected automatically at render time, same as always).
        :param description: One or two plain-language sentences: what this graph does and when to use it. This is what list_workflows shows, so write it for a model deciding whether to reuse this template, not for yourself.
        :param placeholders: Optional JSON object mapping a parameter name you choose (e.g. "positive_prompt", "seed", "denoise", "controlnet_strength") to [node_id, input_name] - the literal (non-link) input in this graph that parameter should overwrite. This is what makes run_workflow's `overrides` argument work later without resending the graph. Omit for a template with no adjustable parameters.
        :param tags: Optional comma-separated tags (e.g. "controlnet,pose") to help list_workflows filtering.
        :param overwrite: Must be true to replace an existing template with this name; otherwise a name collision is an error, to avoid silently clobbering someone else's saved graph.
        """
        try:
            tname = validate_template_name(name)
            graph = parse_workflow(workflow)
            validate_graph_shape(graph)

            placeholders_dict: Dict[str, Any] = {}
            if not is_unset(placeholders):
                try:
                    placeholders_dict = json.loads(placeholders) if isinstance(placeholders, str) else placeholders
                except ValueError as e:
                    raise ValueError(f"placeholders is not valid JSON: {e}") from e
                if not isinstance(placeholders_dict, dict):
                    raise ValueError("placeholders must be a JSON object of parameter name -> [node_id, input_name].")
            normalized_placeholders = validate_placeholders(graph, placeholders_dict)

            if not description or not description.strip():
                raise ValueError("description is required - it's how a model finds this template later without reading its JSON.")

            tag_list = sorted({t.strip().lower() for t in (tags or "").split(",") if t.strip()})

            existing = await asyncio.to_thread(load_workflow_template, self.valves.JOB_DB_PATH, tname)
            if existing and not overwrite:
                return {
                    "success": False,
                    "error": f"A template named {tname!r} already exists (version {existing['version']}: {existing['description']!r}). "
                    "Pass overwrite=true to replace it, or choose a different name.",
                }

            version = await asyncio.to_thread(
                save_workflow_template, self.valves.JOB_DB_PATH, tname, description.strip(), graph,
                normalized_placeholders, ",".join(tag_list), "save_workflow",
            )
        except (ValueError, json.JSONDecodeError) as e:
            return {"success": False, "error": str(e)}

        return {
            "success": True,
            "name": tname,
            "version": version,
            "description": description.strip(),
            "placeholders": normalized_placeholders,
            "tags": tag_list,
            "note": f"Saved. Render it with run_workflow(workflow_id={tname!r}, overrides=...) instead of resending this JSON.",
        }

    async def list_workflows(self, tag: Optional[str] = None, search: Optional[str] = None, limit: int = 20) -> Dict[str, Any]:
        """
        Browse saved workflow templates as a Markdown table (name, version, tags, description) -
        find a reusable graph by what it does, without ever reading its JSON. Call get_workflow if
        you actually need the full graph back (e.g. to inspect or build a variant); to just render
        with one, pass its name straight to run_workflow's workflow_id.

        :param tag: Optional. Only templates whose tags include this one, exactly.
        :param search: Optional. Substring match over name and description.
        :param limit: Maximum rows returned, default 20.
        """
        rows = await asyncio.to_thread(list_workflow_templates, self.valves.JOB_DB_PATH, tag, search, limit)
        if not rows:
            return {
                "success": True,
                "count": 0,
                "table": "No saved workflow templates matched." if (tag or search) else "No workflow templates saved yet.",
            }
        lines = ["| Name | Version | Tags | Description |", "|---|---|---|---|"]
        for r in rows:
            lines.append(f"| {r['name']} | {r['version']} | {r['tags'] or ''} | {_truncate(r['description'], 140)} |")
        return {"success": True, "count": len(rows), "table": "\n".join(lines)}

    async def get_workflow(self, name: str) -> Dict[str, Any]:
        """
        Fetch a saved template's full graph JSON, placeholders, tags and description. Only call
        this when you actually need the graph itself back - to inspect it or build an edited
        variant. To just render with an existing template, pass its name as run_workflow's
        workflow_id instead; that path never needs the JSON back in this chat.

        :param name: The template's name, as shown by list_workflows.
        """
        try:
            tname = validate_template_name(name)
        except ValueError as e:
            return {"success": False, "error": str(e)}
        row = await asyncio.to_thread(load_workflow_template, self.valves.JOB_DB_PATH, tname)
        if not row:
            return {"success": False, "error": f"No template named {tname!r}. Use list_workflows to see what's saved."}
        return {
            "success": True,
            "name": row["name"],
            "version": row["version"],
            "description": row["description"],
            "tags": [t for t in (row["tags"] or "").split(",") if t],
            "placeholders": json.loads(row["placeholders_json"] or "{}"),
            "workflow": json.loads(row["graph_json"]),
            "updated_at": row["updated_at"],
        }

    async def delete_workflow(self, name: str) -> Dict[str, Any]:
        """
        Permanently remove a saved workflow template. Does not affect past renders that used it -
        their exact submitted graph is preserved verbatim in the job database regardless.

        :param name: The template's name, as shown by list_workflows.
        """
        try:
            tname = validate_template_name(name)
        except ValueError as e:
            return {"success": False, "error": str(e)}
        removed = await asyncio.to_thread(delete_workflow_template, self.valves.JOB_DB_PATH, tname)
        if not removed:
            return {"success": False, "error": f"No template named {tname!r}."}
        return {"success": True, "name": tname, "note": "Deleted."}

    async def run_workflow(
        self,
        workflow: Optional[str] = None,
        workflow_id: Optional[str] = None,
        overrides: Optional[str] = None,
        source_image: Optional[str] = None,
        source_server: Optional[str] = None,
        gpu_server: Optional[str] = None,
        return_img_url: bool = False,
        queue_only: bool = False,
        verbose: bool = False,
        __event_emitter__: Optional[Callable[[dict], Any]] = None,
    ) -> Dict[str, Any]:
        """
        Submit a full, custom ComfyUI workflow graph (API/export JSON format: an object of
        node_id -> {"class_type": ..., "inputs": {...}}), for anything the fixed generate_image
        graph can't reach - ControlNet, IP-Adapter, upscaling, compositing, multi-stage pipelines,
        or any other node combination. You build the whole graph, including your own checkpoint
        loader, samplers, and conditioning.

        Pass exactly one of `workflow` (a raw graph, for a new or one-off design) or `workflow_id`
        (a name from list_workflows / save_workflow, to reuse a graph already proven to work,
        without resending its JSON). With `workflow_id`, `overrides` lets you change whichever
        parameters that template registered placeholders for - e.g.
        overrides='{"positive_prompt": "...", "seed": 12345}' - without touching the rest of the
        graph. Once a graph is working, call save_workflow to keep using it this cheaply instead of
        rebuilding or resending it every time.

        TOOLKIT: this is one of three related tools, all sharing the same GPU_SERVERS. Prefer
        generate_image for ordinary SDXL renders (txt2img/img2img, LoRAs) - it's simpler and
        doesn't require building a graph by hand. Use THIS tool only when that fixed graph can't
        do what's needed. Use retrieve_image afterward to fetch a result by job id or filename,
        check a queue_only submission, or list a server's recent jobs. A result's 'server' can be
        passed as gpu_server, and an image's 'use_as_source_image' as source_image, to chain
        across any of the three tools.

        Two things are enforced automatically:
        - The graph MUST contain at least one SaveImage node (fed by your final image output), so a
          render is guaranteed to land in the server's output folder. Missing one is a validation
          error, not a wasted render.
        - A LoadImageOutput node is always present at the fixed id "__comfy_tool_source_image__",
          whether or not this call passes source_image. Wire any of your own nodes to
          ["__comfy_tool_source_image__", 0] to consume it (e.g. a ControlNet preprocessor). If a
          call doesn't set source_image, that node points at a harmless 1x1 placeholder instead of
          being left invalid.

        Any CheckpointLoaderSimple node's ckpt_name is matched against the server's real checkpoint
        list the same way generate_image does (exact, case/path-insensitive, or a unique match by
        filename), so folder or naming differences between servers don't need to be hard-coded.

        :param workflow: The ComfyUI API-format graph as a JSON string. Omit if using workflow_id instead.
        :param workflow_id: The name of a template saved with save_workflow, in place of `workflow`. See list_workflows/get_workflow.
        :param overrides: Only with workflow_id. JSON object of parameter name -> new literal value, for whichever placeholders that template registered (see get_workflow's `placeholders`).
        :param source_image: Optional. A filename in the target server's output folder (e.g. an earlier generate_image or run_workflow result's 'use_as_source_image') to feed into the fixed LoadImageOutput node. Omit to leave that node pointed at the placeholder.
        :param source_server: Only needed when source_image lives on a DIFFERENT server than gpu_server; set it to the server the source image is on and the file is copied across first.
        :param gpu_server: Omit to use the default server. Otherwise a configured server, or (if allowed) any ComfyUI address.
        :param return_img_url: If true, include download URLs for each image: 'comfy_url', 'chat_url', and a ready-made 'link_markdown'.
        :param queue_only: If true, only submit the job and return its job id and queue position (or ComfyUI's error) without waiting for the render.
        :param verbose: Also return the exact graph submitted (after SaveImage/LoadImageOutput preparation) and the server's history entry.
        """
        v = self.valves

        async def status(text: str, done: bool = False):
            await _emit(__event_emitter__, {"type": "status", "data": {"description": text, "done": done}})

        try:
            allowed = list(dict.fromkeys(list(v.GPU_SERVERS) + [v.DEFAULT_GPU_SERVER]))
            server = resolve_server(gpu_server, v.DEFAULT_GPU_SERVER, allowed, v.ALLOW_UNLISTED_SERVERS)
            source_image = None if is_unset(source_image) else source_image.strip()
            source_server = None if is_unset(source_server) else source_server.strip()

            if is_unset(workflow) == is_unset(workflow_id):
                raise ValueError("Pass exactly one of workflow (raw graph JSON) or workflow_id (a saved template's name).")

            template_placeholders: Dict[str, List[str]] = {}
            if not is_unset(workflow_id):
                tname = validate_template_name(workflow_id)
                template_row = await asyncio.to_thread(load_workflow_template, v.JOB_DB_PATH, tname)
                if not template_row:
                    raise ValueError(f"No saved workflow template named {tname!r}. Use list_workflows to see what's available.")
                graph = json.loads(template_row["graph_json"])
                template_placeholders = json.loads(template_row["placeholders_json"] or "{}")
            else:
                tname = None
                graph = parse_workflow(workflow)

            if not is_unset(overrides):
                try:
                    overrides_dict = json.loads(overrides) if isinstance(overrides, str) else overrides
                except ValueError as e:
                    raise ValueError(f"overrides is not valid JSON: {e}") from e
                if not isinstance(overrides_dict, dict):
                    raise ValueError("overrides must be a JSON object of parameter name -> value.")
                if tname is None:
                    raise ValueError("overrides only applies with workflow_id; edit a raw `workflow` graph directly instead.")
                apply_overrides(graph, template_placeholders, overrides_dict)

            graph, needs_placeholder = prepare_graph(graph, v.FILENAME_PREFIX, source_image)

            client = ComfyClient(server, v.REQUEST_TIMEOUT_SECONDS)
            available_ckpts = await asyncio.to_thread(client.list_checkpoints)
            resolved_checkpoints: Dict[str, str] = {}
            if available_ckpts:
                for node_id, node in graph.items():
                    if node.get("class_type") in _CKPT_LOADER_CLASSES and "ckpt_name" in node.get("inputs", {}):
                        wanted = node["inputs"]["ckpt_name"]
                        fixed = resolve_checkpoint(wanted, available_ckpts)
                        if fixed != wanted:
                            resolved_checkpoints[node_id] = f"{wanted!r} -> {fixed!r}"
                        node["inputs"]["ckpt_name"] = fixed

            copied_from = None
            if source_image and not is_unset(source_server):
                resolved_source_server = resolve_server(source_server, server, allowed, v.ALLOW_UNLISTED_SERVERS)
                if resolved_source_server != server:
                    subfolder, filename = parse_source_image(source_image)
                    await status(f"Copying source image from {resolved_source_server}...")
                    await copy_source_image(resolved_source_server, client, subfolder, filename, v.REQUEST_TIMEOUT_SECONDS)
                    copied_from = resolved_source_server

            if needs_placeholder:
                await ensure_placeholder(client, v.REQUEST_TIMEOUT_SECONDS)

            job_uuid = str(uuid.uuid4()) if v.LOG_TO_SQLITE else None
            if job_uuid:
                positive_prompt, negative_prompt = extract_prompts(graph)
                input_json = {
                    "tool": "run_workflow",
                    **({"workflow_id": tname, "overrides": overrides} if tname is not None else {"workflow": workflow}),
                    "source_image": source_image,
                    "source_server": source_server, "gpu_server": gpu_server, "queue_only": queue_only,
                }
                await asyncio.to_thread(
                    record_job_built, v.JOB_DB_PATH, job_uuid, "run_workflow", server,
                    input_json, graph, positive_prompt, negative_prompt,
                )
        except (ValueError, json.JSONDecodeError, ComfyError) as e:
            return {"success": False, "error": str(e)}

        node_labels = {nid: NODE_TYPE_LABELS.get(n.get("class_type", ""), n.get("class_type", "node")) for nid, n in graph.items()}

        if queue_only:
            try:
                await status("Submitting job to the queue...")
                info = await asyncio.to_thread(client.submit_prompt, graph, str(uuid.uuid4()))
                ahead = await asyncio.to_thread(client.jobs_ahead, info.get("number"))
            except ComfyError as e:
                await status(f"Queue rejected the job: {e}", done=True)
                if job_uuid:
                    await asyncio.to_thread(record_job_failed, v.JOB_DB_PATH, job_uuid, "submit", str(e), e.body)
                rejected: Dict[str, Any] = {"success": False, "queued": False, "error": str(e), "server": server}
                if e.body:
                    rejected["server_response"] = e.body
                return rejected
            job_id = info["prompt_id"]
            if job_uuid:
                await asyncio.to_thread(record_job_submitted, v.JOB_DB_PATH, job_uuid, job_id, info)
            await status(f"Queued as job {job_id[:8]}", done=True)
            queued: Dict[str, Any] = {
                "success": True,
                "queued": True,
                "job_id": job_id,
                "queue_number": info.get("number"),
                "jobs_ahead": ahead,
                "server": server,
                "output_filename_prefix": v.FILENAME_PREFIX,
                "note": "The GPU server accepted the job. It was not waited for and no image was delivered; it will be saved in the server's output folder.",
            }
            if info.get("node_errors"):
                queued["node_errors"] = info["node_errors"]
            if resolved_checkpoints:
                queued["checkpoint_notes"] = resolved_checkpoints
            if copied_from:
                queued["source_image_note"] = f"Copied source image from {copied_from} to {server} before queuing."
            if verbose:
                queued["workflow"] = graph
            return queued

        try:
            await status("Rendering...")
            render_completed = False
            result = await client.run(
                graph, v.MAX_WAIT_SECONDS, node_labels, on_status=status, show_progress=v.SHOW_PROGRESS,
                job_uuid=job_uuid, db_path=v.JOB_DB_PATH if job_uuid else None,
            )
            render_completed = True  # the render itself succeeded; anything below is chat delivery

            images_out: List[Dict[str, Any]] = []
            chat_sources: List[str] = []
            warnings: List[str] = []
            for img in result["images"]:
                subfolder = img.get("subfolder", "")
                ref = f"{subfolder}/{img['filename']}" if subfolder else img["filename"]
                comfy_url = client.view_url(img)
                delivered_url, delivery = comfy_url, "direct_comfy_url"

                data: Optional[bytes] = None
                if v.UPLOAD_TO_OPEN_WEBUI or v.SAVE_LOCAL_COPY:
                    try:
                        data = await asyncio.to_thread(client.fetch_image, img)
                    except ComfyError as e:
                        warnings.append(str(e))
                if data is not None and v.SAVE_LOCAL_COPY:
                    out_dir = Path(v.OUTPUT_DIR)
                    out_dir.mkdir(parents=True, exist_ok=True)
                    (out_dir / f"{result['prompt_id'][:8]}_{img['filename']}").write_bytes(data)
                if data is not None and v.UPLOAD_TO_OPEN_WEBUI:
                    path, err = await asyncio.to_thread(upload_to_open_webui, v.OPEN_WEBUI_BASE_URL, v.OPEN_WEBUI_API_KEY, data, img["filename"], v.REQUEST_TIMEOUT_SECONDS)
                    if path:
                        delivered_url, delivery = path, "openwebui_upload"
                    else:
                        warnings.append(f"Open WebUI upload failed ({err}); using a direct ComfyUI link, which only displays if the browser can reach {server}.")

                chat_sources.append(delivered_url)
                entry: Dict[str, Any] = {"filename": img["filename"], "subfolder": subfolder, "delivery": delivery, "use_as_source_image": ref}
                if return_img_url:
                    entry["comfy_url"] = comfy_url
                    entry["chat_url"] = delivered_url
                    entry["link_markdown"] = f"[{img['filename']}]({delivered_url})"
                images_out.append(entry)

            emitted = v.IMAGE_DELIVERY != "model_embed" and bool(__event_emitter__)
            if emitted:
                if v.IMAGE_DELIVERY == "files_event":
                    payload = {"type": "files", "data": {"files": [{"type": "image", "url": u} for u in chat_sources]}}
                else:
                    md = "\n\n".join(f"![generated image]({u})" for u in chat_sources)
                    payload = {"type": "message", "data": {"content": md + "\n\n"}}
                await _emit(__event_emitter__, payload)
            await status("Done", done=True)
        except ComfyError as e:
            logger.error("Graph render failed: %s", e)
            await status(f"Render failed: {e}", done=True)
            # run() already recorded this failure into the job DB at the correct stage.
            return {"success": False, "error": str(e), "server": server}
        except Exception as e:
            logger.exception("Unexpected error during graph render")
            await status("Render failed", done=True)
            if job_uuid and not render_completed:
                await asyncio.to_thread(record_job_failed, v.JOB_DB_PATH, job_uuid, "wait", f"Unexpected error: {e}")
            return {"success": False, "error": f"Unexpected error: {e}", "server": server}

        out: Dict[str, Any] = {
            "success": True,
            "prompt_id": result["prompt_id"],
            "server": server,
            "images": images_out,
            "displayed_via": v.IMAGE_DELIVERY if emitted or v.IMAGE_DELIVERY == "model_embed" else "none",
            "note": (
                "Images are already displayed to the user; don't embed them again. "
                if emitted
                else "Include image_markdown exactly as given in your reply so the user can see the image. "
            ),
        }
        if return_img_url:
            out["note"] += " To show a link to the user, paste link_markdown exactly as given so it renders as a clickable link; don't put URLs in backticks or code blocks."
        if warnings:
            out["warnings"] = warnings
        if resolved_checkpoints:
            out["checkpoint_notes"] = resolved_checkpoints
        if copied_from:
            out["source_image_note"] = f"Copied source image from {copied_from} to {server} before rendering."
        if not emitted:
            out["image_markdown"] = "\n\n".join(f"![generated image]({u})" for u in chat_sources)
        if verbose:
            out["workflow"] = graph
            out["history"] = result["history"]

        log_completed_job(
            v,
            {
                "event": "graph_render_complete",
                "job_id": result["prompt_id"],
                "server": server,
                "filenames": [img["filename"] for img in images_out],
                "workflow": graph,
                **({"copied_source_image_from": copied_from} if copied_from else {}),
            },
        )
        return out
