"""
title: ComfyUI SDXL Direct
author: Gordon
version: 2.2.0
description: Sends prompt text and sampler settings straight to a local ComfyUI server's SDXL graph (txt2img, multi-pass img2img from earlier outputs, optional LoRAs), bypassing any paraphrasing step.
"""

import asyncio
import datetime
import json
import logging
import logging.handlers
import mimetypes
import random
import re
import time
import urllib.parse
import uuid
from pathlib import Path
from typing import Any, Callable, Dict, List, Literal, Optional

import requests
from pydantic import BaseModel, Field
from requests.exceptions import RequestException

logger = logging.getLogger("comfy_sdxl_direct")
logger.setLevel(logging.INFO)

# A separate, dedicated logger for completed-render records (distinct from the
# module logger above, which is for the tool's own diagnostics). Handlers are
# cached per configuration so re-entering generate_image never adds duplicate
# handlers and doesn't duplicate log lines.
_job_logger_cache: Dict[tuple, logging.Logger] = {}


def get_job_logger(v: Any) -> logging.Logger:
    key = (
        v.LOG_BACKEND, v.SYSLOG_ADDRESS, v.SYSLOG_IDENT,
        v.JOB_LOG_PATH, v.JOB_LOG_MAX_BYTES, v.JOB_LOG_BACKUP_COUNT,
    )
    cached = _job_logger_cache.get(key)
    if cached is not None:
        return cached

    job_logger = logging.getLogger(f"comfy_sdxl_direct.jobs.{abs(hash(key))}")
    job_logger.setLevel(logging.INFO)
    job_logger.propagate = False  # keep job records out of the container's general log stream

    wired_syslog = False
    if v.LOG_BACKEND in ("syslog", "both"):
        try:
            handler = logging.handlers.SysLogHandler(address=v.SYSLOG_ADDRESS)
            handler.setFormatter(logging.Formatter(f"{v.SYSLOG_IDENT}: %(message)s"))
            job_logger.addHandler(handler)
            wired_syslog = True
        except OSError as e:
            # Common in containers where /dev/log isn't the host's journald socket.
            logger.warning("Job log: could not open syslog socket %s: %s", v.SYSLOG_ADDRESS, e)

    # Always have a file: it's the explicit backend, or the fallback when syslog didn't wire up.
    if v.LOG_BACKEND in ("file", "both") or not wired_syslog:
        try:
            path = Path(v.JOB_LOG_PATH)
            path.parent.mkdir(parents=True, exist_ok=True)
            handler = logging.handlers.RotatingFileHandler(
                path, maxBytes=v.JOB_LOG_MAX_BYTES, backupCount=v.JOB_LOG_BACKUP_COUNT
            )
            handler.setFormatter(logging.Formatter("%(message)s"))
            job_logger.addHandler(handler)
        except OSError as e:
            logger.warning("Job log: could not open log file %s: %s", v.JOB_LOG_PATH, e)

    _job_logger_cache[key] = job_logger
    return job_logger


def log_completed_job(v: Any, record: Dict[str, Any]) -> None:
    """Best effort: a completed render is never held up or failed by logging trouble."""
    if not v.LOG_JOBS:
        return
    try:
        line = json.dumps({"timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(), **record}, default=str)
        get_job_logger(v).info(line)
    except Exception as e:
        logger.warning("Job log: could not record completed job: %s", e)


# --------------------------------------------------------------------------- #
# SQLite job database - a queryable, verbatim record of every job attempt,
# alongside the syslog/file log above. Design:
#   - job_uuid is generated by the tool BEFORE any network call, so a job that
#     ComfyUI rejects or never responds to is still fully catalogued.
#   - jobs.comfy_prompt_id is filled in once/if the server assigns one, giving
#     a durable link between our id and the server's; it can stay NULL forever
#     for a job the server never saw. comfy_sdxl_retrieve.py's reconciliation
#     logic can backfill it later by matching the 'outputs' graph against a
#     history entry found by filename, for a job that appears server-side
#     without the tool having recorded the link itself.
#   - inputs/outputs/results/errors keep verbatim JSON; prompts and node_params
#     are the broken-out, queryable (non-JSON) columns.
# Shared schema with comfy_sdxl_graph.py and read/written by comfy_sdxl_retrieve.py;
# keep the three in sync by hand if this schema changes.
# --------------------------------------------------------------------------- #

JOB_DB_SCHEMA = """
CREATE TABLE IF NOT EXISTS jobs (
    job_uuid TEXT PRIMARY KEY,
    comfy_prompt_id TEXT,
    tool TEXT NOT NULL,
    server TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    submitted_at TEXT,
    execution_start_ts INTEGER,
    execution_end_ts INTEGER,
    duration_s REAL
);
CREATE INDEX IF NOT EXISTS idx_jobs_comfy_prompt_id ON jobs(comfy_prompt_id);
CREATE INDEX IF NOT EXISTS idx_jobs_server_status ON jobs(server, status);
CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON jobs(created_at);

CREATE TABLE IF NOT EXISTS inputs (
    job_uuid TEXT PRIMARY KEY REFERENCES jobs(job_uuid),
    raw_json TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS outputs (
    job_uuid TEXT PRIMARY KEY REFERENCES jobs(job_uuid),
    raw_json TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_uuid TEXT NOT NULL REFERENCES jobs(job_uuid),
    stage TEXT NOT NULL,
    raw_json TEXT NOT NULL,
    recorded_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_results_job_uuid ON results(job_uuid);

CREATE TABLE IF NOT EXISTS errors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_uuid TEXT NOT NULL REFERENCES jobs(job_uuid),
    stage TEXT NOT NULL,
    message TEXT NOT NULL,
    raw_json TEXT,
    recorded_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_errors_job_uuid ON errors(job_uuid);

CREATE TABLE IF NOT EXISTS prompts (
    job_uuid TEXT PRIMARY KEY REFERENCES jobs(job_uuid),
    positive_prompt TEXT,
    negative_prompt TEXT
);

CREATE TABLE IF NOT EXISTS node_params (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_uuid TEXT NOT NULL REFERENCES jobs(job_uuid),
    node_id TEXT NOT NULL,
    class_type TEXT NOT NULL,
    param_name TEXT NOT NULL,
    value_text TEXT,
    value_num REAL
);
CREATE INDEX IF NOT EXISTS idx_node_params_job_uuid ON node_params(job_uuid);
CREATE INDEX IF NOT EXISTS idx_node_params_lookup ON node_params(class_type, param_name, value_text);
"""
PROMPTS_FTS_SCHEMA = "CREATE VIRTUAL TABLE IF NOT EXISTS prompts_fts USING fts5(job_uuid UNINDEXED, positive_prompt, negative_prompt);"

JOB_DB_BUSY_TIMEOUT_S = 5.0
_job_db_schema_ready: set = set()  # db_path values confirmed (this process) to have the schema


def job_db_connect(db_path: str):
    """A short-lived connection with the schema ensured. Caller must close() it."""
    import sqlite3

    Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path, timeout=JOB_DB_BUSY_TIMEOUT_S)
    conn.execute("PRAGMA journal_mode=WAL;")
    if db_path not in _job_db_schema_ready:
        conn.executescript(JOB_DB_SCHEMA)
        try:
            conn.execute(PROMPTS_FTS_SCHEMA)
        except Exception:  # sqlite3.OperationalError if this build lacks FTS5; search falls back to LIKE
            pass
        _job_db_schema_ready.add(db_path)
    return conn


def _now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def extract_node_params(graph: Dict[str, Any]) -> List[tuple]:
    """(node_id, class_type, param_name, value_text, value_num) for every scalar input in the
    graph. List-typed inputs are links to other nodes (e.g. ["12", 0]), not literal values, and
    are skipped - this only captures the literal parameters actually set on each node."""
    rows = []
    for node_id, node in graph.items():
        class_type = node.get("class_type", "")
        for name, value in (node.get("inputs") or {}).items():
            if isinstance(value, list):  # a link to another node's output, not a literal
                continue
            value_num = value if isinstance(value, (int, float)) and not isinstance(value, bool) else None
            rows.append((str(node_id), str(class_type), str(name), json.dumps(value) if not isinstance(value, str) else value, value_num))
    return rows


def has_prompts_fts(conn) -> bool:
    try:
        conn.execute("SELECT 1 FROM prompts_fts LIMIT 0;")
        return True
    except Exception:
        return False


def record_job_built(
    db_path: str,
    job_uuid: str,
    tool: str,
    server: str,
    input_json: Dict[str, Any],
    output_graph: Dict[str, Any],
    positive_prompt: Optional[str],
    negative_prompt: Optional[str],
) -> None:
    """
    First write for a job, made as soon as the graph is fully built - before it is ever sent
    to ComfyUI. This is what guarantees a job is catalogued even if the server rejects it or
    never responds at all.
    """
    try:
        conn = job_db_connect(db_path)
        try:
            now = _now_iso()
            conn.execute(
                "INSERT INTO jobs (job_uuid, tool, server, status, created_at) VALUES (?, ?, ?, 'built', ?)",
                (job_uuid, tool, server, now),
            )
            conn.execute(
                "INSERT INTO inputs (job_uuid, raw_json, recorded_at) VALUES (?, ?, ?)",
                (job_uuid, json.dumps(input_json, default=str), now),
            )
            conn.execute(
                "INSERT INTO outputs (job_uuid, raw_json, recorded_at) VALUES (?, ?, ?)",
                (job_uuid, json.dumps(output_graph, default=str), now),
            )
            conn.execute(
                "INSERT INTO prompts (job_uuid, positive_prompt, negative_prompt) VALUES (?, ?, ?)",
                (job_uuid, positive_prompt, negative_prompt),
            )
            if has_prompts_fts(conn):
                conn.execute(
                    "INSERT INTO prompts_fts (job_uuid, positive_prompt, negative_prompt) VALUES (?, ?, ?)",
                    (job_uuid, positive_prompt or "", negative_prompt or ""),
                )
            conn.executemany(
                "INSERT INTO node_params (job_uuid, node_id, class_type, param_name, value_text, value_num) VALUES (?, ?, ?, ?, ?, ?)",
                [(job_uuid, *row) for row in extract_node_params(output_graph)],
            )
            conn.commit()
        finally:
            conn.close()
    except Exception as e:
        logger.warning("Job DB: could not record built job %s: %s", job_uuid, e)


def record_job_submitted(db_path: str, job_uuid: str, comfy_prompt_id: str, submit_response: Dict[str, Any]) -> None:
    """Second write: the server accepted the job and assigned it a prompt_id."""
    try:
        conn = job_db_connect(db_path)
        try:
            now = _now_iso()
            conn.execute(
                "UPDATE jobs SET comfy_prompt_id = ?, status = 'queued', submitted_at = ? WHERE job_uuid = ?",
                (comfy_prompt_id, now, job_uuid),
            )
            conn.execute(
                "INSERT INTO results (job_uuid, stage, raw_json, recorded_at) VALUES (?, 'submit_response', ?, ?)",
                (job_uuid, json.dumps(submit_response, default=str), now),
            )
            conn.commit()
        finally:
            conn.close()
    except Exception as e:
        logger.warning("Job DB: could not record submitted job %s: %s", job_uuid, e)


def _execution_timing(history_entry: Dict[str, Any]) -> "tuple[Optional[int], Optional[int], Optional[float]]":
    """(start_ts_ms, end_ts_ms, duration_s), all None if the timestamps aren't present."""
    start_ts = end_ts = None
    for name, data in (history_entry.get("status") or {}).get("messages", []):
        ts = data.get("timestamp") if isinstance(data, dict) else None
        if name == "execution_start" and isinstance(ts, (int, float)):
            start_ts = int(ts)
        elif name in ("execution_success", "execution_error", "execution_interrupted") and isinstance(ts, (int, float)):
            end_ts = int(ts)
    duration = (end_ts - start_ts) / 1000 if start_ts is not None and end_ts is not None else None
    return start_ts, end_ts, duration


def record_job_completed(db_path: str, job_uuid: str, history_entry: Dict[str, Any]) -> None:
    """Final write on success: ComfyUI's history entry, with its own reported timing."""
    try:
        start_ts, end_ts, duration = _execution_timing(history_entry)
        conn = job_db_connect(db_path)
        try:
            now = _now_iso()
            conn.execute(
                "UPDATE jobs SET status = 'completed', execution_start_ts = ?, execution_end_ts = ?, duration_s = ? WHERE job_uuid = ?",
                (start_ts, end_ts, duration, job_uuid),
            )
            conn.execute(
                "INSERT INTO results (job_uuid, stage, raw_json, recorded_at) VALUES (?, 'history', ?, ?)",
                (job_uuid, json.dumps(history_entry, default=str), now),
            )
            conn.commit()
        finally:
            conn.close()
    except Exception as e:
        logger.warning("Job DB: could not record completed job %s: %s", job_uuid, e)


def record_job_failed(db_path: str, job_uuid: str, stage: str, message: str, raw_json: Optional[Dict[str, Any]] = None) -> None:
    """
    Final write on failure: rejected by the server (stage='submit'), or accepted but never
    finished (stage='wait' - timeout, lost connection, or an execution_error from the server).
    """
    status = "rejected" if stage == "submit" else "failed"
    try:
        conn = job_db_connect(db_path)
        try:
            now = _now_iso()
            conn.execute("UPDATE jobs SET status = ? WHERE job_uuid = ?", (status, job_uuid))
            conn.execute(
                "INSERT INTO errors (job_uuid, stage, message, raw_json, recorded_at) VALUES (?, ?, ?, ?, ?)",
                (job_uuid, stage, message, json.dumps(raw_json, default=str) if raw_json is not None else None, now),
            )
            conn.commit()
        finally:
            conn.close()
    except Exception as e:
        logger.warning("Job DB: could not record failed job %s: %s", job_uuid, e)

# NOTE: Open WebUI exposes *every* public/single-underscore callable on the
# `Tools` class to the model as a tool. All helpers therefore live at module
# level (or in ComfyClient) so that `generate_image` is the only tool exposed.

POLL_INTERVAL_SECONDS = 1.0
DEFAULT_TXT2IMG_DENOISE = 1.0
DEFAULT_IMG2IMG_DENOISE = 0.6
SAVE_NODE_ID = "7"

_ANNOTATION_RE = re.compile(r"\s*\[(\w+)\]\s*$")


class ComfyError(Exception):
    """Raised for anything that goes wrong talking to / running on ComfyUI."""

    def __init__(self, message: str, body: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.body = body  # ComfyUI's raw error response, when there was one


# --------------------------------------------------------------------------- #
# Graph construction (pure functions, no I/O)
# --------------------------------------------------------------------------- #

def parse_source_image(ref: str) -> "tuple[str, str]":
    """
    Turn whatever the model hands us into (subfolder, filename) of a file in
    ComfyUI's output folder. Accepts a bare filename, "subfolder/filename",
    an already-annotated value, a ComfyUI /view URL, or a markdown image
    pointing at one.
    """
    text = (ref or "").strip()

    md = re.search(r"\((https?://[^)\s]+)\)", text)
    if md:
        text = md.group(1)

    if text.startswith(("http://", "https://")):
        query = urllib.parse.parse_qs(urllib.parse.urlparse(text).query)
        filename = (query.get("filename") or [""])[0]
        if not filename:
            raise ValueError("source_image URL has no 'filename' parameter.")
        if (query.get("type") or ["output"])[0] != "output":
            raise ValueError("source_image must be in the ComfyUI output folder.")
        subfolder = (query.get("subfolder") or [""])[0]
        text = f"{subfolder}/{filename}" if subfolder else filename

    annotation = _ANNOTATION_RE.search(text)
    if annotation:
        if annotation.group(1) != "output":
            raise ValueError("source_image must be in the ComfyUI output folder.")
        text = text[: annotation.start()]

    text = text.replace("\\", "/").strip("/")
    parts = text.split("/")
    if not text or ".." in parts:
        raise ValueError(f"Invalid source_image: {ref!r}")
    return "/".join(parts[:-1]), parts[-1]


def normalize_source_image(ref: str) -> str:
    """Turn a source_image reference into the annotated path LoadImageOutput expects."""
    subfolder, filename = parse_source_image(ref)
    return f"{subfolder}/{filename} [output]" if subfolder else f"{filename} [output]"


_UNSET_STRINGS = {"", "default", "auto", "none", "null", "undefined", "n/a"}


def is_unset(value: Any) -> bool:
    """True for None or placeholder strings models like to send for 'not provided'."""
    return value is None or (isinstance(value, str) and value.strip().lower() in _UNSET_STRINGS)


def resolve_server(
    requested: Optional[str], default: str, allowed: List[str], allow_unlisted: bool = False
) -> str:
    """
    Pick the ComfyUI server. Unset/placeholder -> default. A URL/host matching
    a configured server -> that server. Anything else is accepted as-is if
    allow_unlisted is on (any well-formed http(s) address; a missing port
    defaults to ComfyUI's 8188), else rejected.
    """
    allowed_norm = [s.rstrip("/") for s in allowed]
    if is_unset(requested):
        return default.rstrip("/")

    wanted = requested.strip()
    if wanted.endswith("/") and not wanted.endswith("://"):  # trim a trailing slash without
        wanted = wanted[:-1]                                  # eating the "//" of the scheme itself
    if wanted in allowed_norm:
        return wanted

    # Allow "100.95.85.50" or "100.95.85.50:8188" without the scheme.
    with_scheme = wanted if "://" in wanted else f"http://{wanted}"
    parsed = urllib.parse.urlparse(with_scheme)
    for server in allowed_norm:
        s = urllib.parse.urlparse(server)
        if parsed.hostname == s.hostname and (parsed.port is None or parsed.port == s.port):
            return server

    if allow_unlisted:
        if parsed.scheme not in ("http", "https") or not parsed.hostname:
            raise ValueError(f"gpu_server {requested!r} is not a valid http(s) address.")
        try:
            port = parsed.port
        except ValueError:
            raise ValueError(f"gpu_server {requested!r} has an invalid port.") from None
        host = f"[{parsed.hostname}]" if ":" in parsed.hostname else parsed.hostname
        return f"{parsed.scheme}://{host}:{port or 8188}"  # origin only; any path/credentials are dropped

    raise ValueError(
        f"Unknown gpu_server {requested!r}. Omit it to use the default, choose one of {allowed_norm}, "
        "or enable the ALLOW_UNLISTED_SERVERS valve."
    )


_CKPT_EXT_RE = re.compile(r"\.(safetensors|ckpt|pt|pth|bin|sft)$", re.I)


def _ckpt_basename(name: str) -> str:
    return name.replace("\\", "/").rsplit("/", 1)[-1]


def _ckpt_key(name: str) -> str:
    """Lowercase alphanumerics of the file name without folder or extension."""
    return re.sub(r"[^a-z0-9]", "", _CKPT_EXT_RE.sub("", _ckpt_basename(name)).lower())


def resolve_checkpoint(requested: str, available: List[str]) -> str:
    """
    Map a requested checkpoint name onto one that really exists on the server.

    Tries, in order: exact match; match ignoring case and path separators;
    same file name in a different folder; a unique fuzzy match on the file
    name (so "EpicRealism XL" can find "epicrealismXL_pureFix.safetensors").
    Anything ambiguous or missing raises ValueError listing what is available.
    """
    if requested in available:
        return requested

    norm = requested.replace("\\", "/").strip().lower()
    for a in available:
        if a.replace("\\", "/").lower() == norm:
            return a

    base = _ckpt_basename(requested).strip().lower()
    same_base = [a for a in available if _ckpt_basename(a).lower() == base]
    if len(same_base) == 1:
        return same_base[0]

    key = _ckpt_key(requested)
    fuzzy = [a for a in available if key and key in _ckpt_key(a)]
    if not same_base and len(fuzzy) == 1:
        return fuzzy[0]

    ambiguous = same_base or fuzzy
    if ambiguous:
        raise ValueError(
            f"Checkpoint {requested!r} is ambiguous on this server; it could be any of: {sorted(ambiguous)}. "
            "Pass checkpoint_name with the exact filename."
        )
    shown = sorted(available)[:80]
    more = f" (+{len(available) - 80} more)" if len(available) > 80 else ""
    raise ValueError(
        f"Checkpoint {requested!r} was not found on this server. Available checkpoints: {shown}{more}. "
        "Pass checkpoint_name with one of these exactly, or update the DEFAULT_CHECKPOINT valve."
    )


def build_lora_inputs(loras: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Build the widget inputs for the rgthree Power Lora Loader (node 27)."""
    inputs: Dict[str, Any] = {
        "PowerLoraLoaderHeaderWidget": {"type": "PowerLoraLoaderHeaderWidget"}
    }
    for i, cfg in enumerate(loras, start=1):
        if not isinstance(cfg, dict):
            raise ValueError("Each LoRA must be an object like {'lora': 'name.safetensors', 'strength': 0.8}.")
        name = cfg.get("lora") or cfg.get("name")
        if not name:
            raise ValueError(f"LoRA #{i} is missing the 'lora' filename.")
        strength_two = cfg.get("strength_two")
        inputs[f"lora_{i}"] = {
            "on": bool(cfg.get("on", True)),
            "lora": str(name),
            "strength": float(cfg.get("strength", 1.0)),
            # The graph runs the loader in "Single Strength" mode, where
            # strengthTwo is null.
            "strengthTwo": None if strength_two is None else float(strength_two),
        }
    inputs["➕ Add Lora"] = ""
    return inputs


def build_workflow(
    *,
    positive_prompt: str,
    negative_prompt: str,
    checkpoint_name: str,
    seed: int,
    steps: int,
    cfg: float,
    sampler_name: str,
    scheduler: str,
    denoise: float,
    width: int,
    height: int,
    batch_size: int,
    source_image: Optional[str] = None,
    loras: Optional[List[Dict[str, Any]]] = None,
    filename_prefix: str = "sdxl_simple",
) -> Dict[str, Any]:
    """
    Build the ComfyUI *API-format* prompt for the SDXL graph.

    Node ids match the saved graph:
      10/11 CLIPTextEncode (pos/neg)   12 KSampler        13 EmptyLatentImage
      14 VAEDecode                     15 CheckpointLoader  27 Power Lora Loader
      30 VAEEncode                     32 LoadImageOutput   7  SaveImage
    Added: 36 RepeatLatentBatch (img2img batches only).

    Differences from the GUI graph:
      * Node 35 (input switch) is not used - the KSampler latent is wired
        directly to node 13 (txt2img) or node 30/36 (img2img).
      * Node 27 is only inserted when LoRAs are requested (in the GUI graph it
        is bypassed).
    """
    wf: Dict[str, Any] = {}

    wf["15"] = {
        "class_type": "CheckpointLoaderSimple",
        "inputs": {"ckpt_name": checkpoint_name},
    }

    # Model / CLIP source: straight from the checkpoint, or via LoRA loader.
    if loras:
        lora_inputs = build_lora_inputs(loras)
        lora_inputs["model"] = ["15", 0]
        lora_inputs["clip"] = ["15", 1]
        wf["27"] = {"class_type": "Power Lora Loader (rgthree)", "inputs": lora_inputs}
        model_src, clip_src = ["27", 0], ["27", 1]
    else:
        model_src, clip_src = ["15", 0], ["15", 1]

    wf["10"] = {
        "class_type": "CLIPTextEncode",
        "inputs": {"clip": clip_src, "text": positive_prompt},
    }
    wf["11"] = {
        "class_type": "CLIPTextEncode",
        "inputs": {"clip": clip_src, "text": negative_prompt},
    }

    # Latent source
    if source_image:
        wf["32"] = {
            "class_type": "LoadImageOutput",
            "inputs": {"image": normalize_source_image(source_image)},
        }
        wf["30"] = {
            "class_type": "VAEEncode",
            "inputs": {"pixels": ["32", 0], "vae": ["15", 2]},
        }
        latent_src = ["30", 0]
        if batch_size > 1:
            wf["36"] = {
                "class_type": "RepeatLatentBatch",
                "inputs": {"samples": ["30", 0], "amount": batch_size},
            }
            latent_src = ["36", 0]
    else:
        wf["13"] = {
            "class_type": "EmptyLatentImage",
            "inputs": {"width": width, "height": height, "batch_size": batch_size},
        }
        latent_src = ["13", 0]

    wf["12"] = {
        "class_type": "KSampler",
        "inputs": {
            "model": model_src,
            "positive": ["10", 0],
            "negative": ["11", 0],
            "latent_image": latent_src,
            "seed": seed,
            "steps": steps,
            "cfg": cfg,
            "sampler_name": sampler_name,
            "scheduler": scheduler,
            "denoise": denoise,
        },
    }
    wf["14"] = {
        "class_type": "VAEDecode",
        "inputs": {"samples": ["12", 0], "vae": ["15", 2]},
    }
    wf[SAVE_NODE_ID] = {
        "class_type": "SaveImage",
        "inputs": {"images": ["14", 0], "filename_prefix": filename_prefix},
    }
    return wf


# --------------------------------------------------------------------------- #
# ComfyUI HTTP client
# --------------------------------------------------------------------------- #

def _format_prompt_error(body: Dict[str, Any]) -> str:
    """Turn a ComfyUI /prompt 400 body into something a model (or human) can act on."""
    parts = []
    err = body.get("error")
    if isinstance(err, dict):
        parts.append(err.get("message") or err.get("type") or "prompt rejected")
        if err.get("details"):
            parts.append(str(err["details"]))
    elif err:
        parts.append(str(err))
    for node_id, info in (body.get("node_errors") or {}).items():
        for e in info.get("errors", []):
            parts.append(
                f"node {node_id} ({info.get('class_type', '?')}): "
                f"{e.get('message', '')} {e.get('details', '')}".strip()
            )
    return "; ".join(p for p in parts if p) or "ComfyUI rejected the prompt."


def _format_execution_error(status: Dict[str, Any]) -> str:
    for name, data in status.get("messages", []):
        if name == "execution_error":
            return (
                f"{data.get('node_type', 'node')} {data.get('node_id', '?')}: "
                f"{data.get('exception_message', 'execution failed')}".strip()
            )
    return "ComfyUI reported an execution error."


# Friendly names for the nodes in our graph, used for progress messages.
NODE_LABELS = {
    "15": "Loading checkpoint",
    "27": "Applying LoRAs",
    "10": "Encoding prompt",
    "11": "Encoding negative prompt",
    "32": "Loading source image",
    "30": "Encoding source image",
    "36": "Batching latents",
    "13": "Preparing latent",
    "12": "Sampling",
    "14": "Decoding image",
    "7": "Saving image",
}
PROGRESS_MIN_INTERVAL_SECONDS = 0.3
WS_CONNECT_WAIT_SECONDS = 2.0


def progress_message(
    event: Dict[str, Any],
    state: Dict[str, Any],
    prompt_id: Optional[str] = None,
    now: Optional[float] = None,
) -> Optional[str]:
    """
    Turn one ComfyUI websocket event into a short status line, or None.
    `state` is per-run scratch space (which node is running, throttling, ...).
    """
    etype = event.get("type")
    data = event.get("data") or {}

    pid = data.get("prompt_id")
    if pid and prompt_id and pid != prompt_id:
        return None

    if etype == "status":
        remaining = ((data.get("status") or {}).get("exec_info") or {}).get("queue_remaining")
        if isinstance(remaining, int) and remaining > 1 and not state.get("started"):
            return f"Queued: {remaining - 1} job(s) ahead of this one"
        return None

    if etype == "execution_start":
        state["started"] = True
        return "Starting..."

    if etype == "executing":
        node = data.get("node")
        if node is None:  # end-of-run marker
            return None
        state["started"] = True
        state["node"] = str(node)
        label = NODE_LABELS.get(str(node))
        return f"{label}..." if label else None

    if etype == "progress":
        value, maximum = data.get("value"), data.get("max")
        if not (isinstance(value, int) and isinstance(maximum, int) and maximum > 0):
            return None
        state["started"] = True
        t = time.monotonic() if now is None else now
        if value < maximum and t - state.get("last_progress", float("-inf")) < PROGRESS_MIN_INTERVAL_SECONDS:
            return None  # throttle; the final step always goes through
        state["last_progress"] = t
        node = str(data.get("node") or state.get("node") or "")
        label = NODE_LABELS.get(node, "Working")
        return f"{label}: step {value}/{maximum} ({round(100 * value / maximum)}%)"

    return None


class ComfyClient:
    def __init__(self, base_url: str, timeout: int):
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.lookup_error: Optional[str] = None

    def submit_prompt(self, workflow: Dict[str, Any], client_id: str) -> Dict[str, Any]:
        """POST /prompt. Returns ComfyUI's response ({'prompt_id', 'number', 'node_errors'})."""
        try:
            r = requests.post(
                f"{self.base_url}/prompt",
                json={"prompt": workflow, "client_id": client_id},
                timeout=self.timeout,
            )
        except RequestException as e:
            raise ComfyError(f"Cannot reach ComfyUI at {self.base_url}: {e}") from e
        if r.status_code != 200:
            try:
                body = r.json()
            except ValueError:
                body = {"error": r.text[:500]}
            raise ComfyError(_format_prompt_error(body), body=body)
        return r.json()

    def queue_prompt(self, workflow: Dict[str, Any], client_id: str) -> str:
        return self.submit_prompt(workflow, client_id)["prompt_id"]

    def jobs_ahead(self, number: Any) -> Optional[int]:
        """
        How many jobs (including a running one) were queued before ours.
        Best effort: None if the server's /queue can't be read.
        """
        if not isinstance(number, int):
            return None
        try:
            r = requests.get(f"{self.base_url}/queue", timeout=self.timeout)
            r.raise_for_status()
            q = r.json()
            items = list(q.get("queue_running", [])) + list(q.get("queue_pending", []))
            return sum(
                1
                for it in items
                if isinstance(it, (list, tuple)) and it and isinstance(it[0], int) and it[0] < number
            )
        except (RequestException, ValueError, AttributeError, TypeError):
            return None

    def list_checkpoints(self) -> List[str]:
        """
        Checkpoint filenames the server knows about. Best effort: returns [] if
        the server can't tell us, and records why in self.lookup_error.
        """
        self.lookup_error = None
        try:
            r = requests.get(f"{self.base_url}/object_info/CheckpointLoaderSimple", timeout=self.timeout)
            r.raise_for_status()
            spec = r.json()["CheckpointLoaderSimple"]["input"]["required"]["ckpt_name"]
            names: List[str] = []
            if isinstance(spec[0], list):
                names = [str(x) for x in spec[0]]
            elif spec[0] == "COMBO" and len(spec) > 1:  # newer ComfyUI schema
                names = [str(x) for x in spec[1].get("options", [])]
            if not names:
                self.lookup_error = "server returned no checkpoint list in a format this tool understands"
            return names
        except (RequestException, KeyError, IndexError, TypeError, ValueError) as e:
            self.lookup_error = f"{type(e).__name__}: {e}"
            logger.warning("Could not list checkpoints on %s: %s", self.base_url, self.lookup_error)
        return []

    def get_history(self, prompt_id: str) -> Optional[Dict[str, Any]]:
        try:
            r = requests.get(f"{self.base_url}/history/{prompt_id}", timeout=self.timeout)
            r.raise_for_status()
            return r.json().get(prompt_id)
        except RequestException as e:
            raise ComfyError(f"Lost contact with ComfyUI while waiting: {e}") from e

    def view_url(self, image: Dict[str, Any]) -> str:
        query = urllib.parse.urlencode(
            {
                "filename": image["filename"],
                "subfolder": image.get("subfolder", ""),
                "type": image.get("type", "output"),
            }
        )
        return f"{self.base_url}/view?{query}"

    def fetch_image(self, image: Dict[str, Any]) -> bytes:
        try:
            r = requests.get(self.view_url(image), timeout=self.timeout)
            r.raise_for_status()
            return r.content
        except RequestException as e:
            raise ComfyError(f"Could not download {image['filename']}: {e}") from e

    def upload_image(
        self, image_bytes: bytes, filename: str, subfolder: str = "", type_: str = "output"
    ) -> Dict[str, str]:
        """POST /upload/image. `type_` picks which folder ('input' or 'output') it lands in."""
        try:
            r = requests.post(
                f"{self.base_url}/upload/image",
                files={"image": (filename, image_bytes, mimetypes.guess_type(filename)[0] or "image/png")},
                data={"subfolder": subfolder, "type": type_, "overwrite": "true"},
                timeout=self.timeout,
            )
            r.raise_for_status()
            data = r.json()
        except RequestException as e:
            raise ComfyError(f"Could not upload {filename} to {self.base_url}: {e}") from e
        except ValueError as e:
            raise ComfyError(f"Unexpected upload response from {self.base_url}: {e}") from e
        return {
            "filename": data.get("name", filename),
            "subfolder": data.get("subfolder", subfolder),
            "type": data.get("type", type_),
        }

    async def _listen_progress(
        self,
        client_id: str,
        prompt_box: Dict[str, Optional[str]],
        on_status: Callable[[str], Any],
        connected: asyncio.Event,
    ) -> None:
        """
        Best-effort: relay ComfyUI's websocket progress events as status lines.
        Never raises - completion is still detected by polling /history.
        """
        try:
            import aiohttp  # ships with Open WebUI
        except ImportError:
            connected.set()
            return

        ws_url = f"{self.base_url.replace('http', 'ws', 1)}/ws?clientId={client_id}"
        state: Dict[str, Any] = {}
        try:
            timeout = aiohttp.ClientTimeout(total=None, sock_connect=self.timeout)
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.ws_connect(ws_url, max_msg_size=16 * 1024 * 1024) as ws:
                    connected.set()
                    async for msg in ws:
                        if msg.type in (aiohttp.WSMsgType.CLOSED, aiohttp.WSMsgType.ERROR):
                            break
                        if msg.type != aiohttp.WSMsgType.TEXT:
                            continue  # binary frames are latent previews
                        try:
                            event = json.loads(msg.data)
                        except ValueError:
                            continue
                        text = progress_message(event, state, prompt_box.get("id"))
                        if text:
                            await on_status(text)
        except asyncio.CancelledError:
            raise
        except Exception as e:  # progress is a nicety, never a failure
            logger.debug("Progress websocket unavailable on %s: %s", self.base_url, e)
        finally:
            connected.set()

    async def run(
        self,
        workflow: Dict[str, Any],
        max_wait: int,
        on_status: Optional[Callable[[str], Any]] = None,
        show_progress: bool = True,
        job_uuid: Optional[str] = None,
        db_path: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Queue the workflow and wait for it. Returns {'prompt_id', 'images', 'history'}.
        If job_uuid and db_path are given, records every stage (submitted, completed, or
        failed/rejected at the correct stage) into the job database as it happens.
        """
        client_id = str(uuid.uuid4())
        prompt_box: Dict[str, Optional[str]] = {"id": None}

        # Connect the progress socket *before* queuing so early events aren't missed.
        listener: Optional["asyncio.Task[None]"] = None
        if on_status and show_progress:
            connected = asyncio.Event()
            listener = asyncio.create_task(self._listen_progress(client_id, prompt_box, on_status, connected))
            try:
                await asyncio.wait_for(connected.wait(), timeout=WS_CONNECT_WAIT_SECONDS)
            except asyncio.TimeoutError:
                pass

        try:
            try:
                submit_response = await asyncio.to_thread(self.submit_prompt, workflow, client_id)
            except ComfyError as e:
                if job_uuid and db_path:
                    await asyncio.to_thread(record_job_failed, db_path, job_uuid, "submit", str(e), e.body)
                raise
            prompt_id = submit_response["prompt_id"]
            prompt_box["id"] = prompt_id
            if on_status:
                await on_status(f"Queued on {self.base_url} (prompt {prompt_id[:8]})...")
            if job_uuid and db_path:
                await asyncio.to_thread(record_job_submitted, db_path, job_uuid, prompt_id, submit_response)

            try:
                deadline = time.monotonic() + max_wait
                while True:
                    entry = await asyncio.to_thread(self.get_history, prompt_id)
                    if entry:
                        status = entry.get("status", {})
                        if status.get("status_str") == "error":
                            raise ComfyError(_format_execution_error(status))
                        if status.get("completed") or entry.get("outputs"):
                            break
                    if time.monotonic() > deadline:
                        raise ComfyError(
                            f"Timed out after {max_wait}s (prompt {prompt_id} may still be running on the server)."
                        )
                    await asyncio.sleep(POLL_INTERVAL_SECONDS)
            except ComfyError as e:
                if job_uuid and db_path:
                    await asyncio.to_thread(record_job_failed, db_path, job_uuid, "wait", str(e))
                raise
        finally:
            if listener:
                listener.cancel()
                # return_exceptions=True absorbs the listener's own CancelledError
                # without hiding a cancellation of the surrounding call.
                await asyncio.gather(listener, return_exceptions=True)

        images = [
            img
            for img in entry.get("outputs", {}).get(SAVE_NODE_ID, {}).get("images", [])
            if img.get("type", "output") == "output"
        ]
        if not images:
            if job_uuid and db_path:
                await asyncio.to_thread(record_job_failed, db_path, job_uuid, "wait", "Workflow finished but produced no images.")
            raise ComfyError("Workflow finished but produced no images.")
        if job_uuid and db_path:
            await asyncio.to_thread(record_job_completed, db_path, job_uuid, entry)
        return {"prompt_id": prompt_id, "images": images, "history": entry}



def upload_to_open_webui(
    base_url: str, api_key: str, image_bytes: bytes, filename: str, timeout: int
) -> "tuple[Optional[str], Optional[str]]":
    """
    Store an image in Open WebUI's own file storage via its REST API so the
    browser only ever needs to reach Open WebUI itself (works through
    Tailscale / any reverse proxy, no mixed-content problems).

    Returns (relative_url, None) on success or (None, error_text) on failure.
    The relative URL resolves against whatever host the browser is using.
    """
    if not api_key:
        return None, "OPEN_WEBUI_API_KEY is empty in the tool's valves"
    try:
        resp = requests.post(
            f"{base_url.rstrip('/')}/api/v1/files/",
            headers={"Authorization": f"Bearer {api_key}"},
            files={"file": (filename, image_bytes, mimetypes.guess_type(filename)[0] or "image/png")},
            # Images have no text to extract/embed; skipping Open WebUI's RAG
            # processing avoids a pointless (and error-logging) background job.
            # Older versions simply ignore the parameter.
            params={"process": "false"},
            timeout=timeout,
        )
        resp.raise_for_status()
        file_id = resp.json().get("id")
        if not file_id:
            return None, f"upload response had no 'id' field: {str(resp.text)[:200]}"
        return f"/api/v1/files/{file_id}/content", None
    except RequestException as e:
        detail = ""
        response = getattr(e, "response", None)
        if response is not None:
            detail = f" (HTTP {response.status_code}: {str(response.text)[:200]})"
        return None, f"{e}{detail}"
    except ValueError as e:  # non-JSON response
        return None, f"unexpected response from Open WebUI: {e}"



async def copy_source_image(
    source_server: str, target_client: "ComfyClient", subfolder: str, filename: str, timeout: int
) -> None:
    """Download filename from source_server's output folder and upload it into target_client's."""
    src = ComfyClient(source_server, timeout)
    image = {"filename": filename, "subfolder": subfolder, "type": "output"}
    data = await asyncio.to_thread(src.fetch_image, image)
    await asyncio.to_thread(target_client.upload_image, data, filename, subfolder, "output")


async def _emit(emitter: Optional[Callable], payload: Dict[str, Any]) -> None:
    if emitter:
        await emitter(payload)


# --------------------------------------------------------------------------- #
# Open WebUI tool
# --------------------------------------------------------------------------- #

class Tools:
    class Valves(BaseModel):
        GPU_SERVERS: List[str] = Field(
            default=["http://192.168.10.11:8188", "http://192.168.10.12:8188"],
            description="ComfyUI servers the model is allowed to target.",
        )
        DEFAULT_GPU_SERVER: str = Field(
            default="http://192.168.10.11:8188",
            description="Server used when the model doesn't pick one.",
        )
        DEFAULT_CHECKPOINT: str = Field(
            default="checkpoints/epicrealismXL_pureFix.safetensors",
            description="Checkpoint used when the model doesn't pick one.",
        )
        FILENAME_PREFIX: str = Field(
            default="sdxl_simple",
            description="SaveImage filename_prefix on the ComfyUI server.",
        )
        OUTPUT_DIR: str = Field(
            default="/app/backend/data/comfy_outputs",
            description="Where local copies are written when SAVE_LOCAL_COPY is on.",
        )
        SAVE_LOCAL_COPY: bool = Field(
            default=False,
            description="Also keep a copy of each result in OUTPUT_DIR.",
        )
        UPLOAD_TO_OPEN_WEBUI: bool = Field(
            default=True,
            description="Upload each result into Open WebUI's own file storage and show it from there, so your browser never has to reach the GPU server. Needs OPEN_WEBUI_API_KEY. If the upload fails, the tool falls back to a direct ComfyUI link.",
        )
        OPEN_WEBUI_BASE_URL: str = Field(
            default="http://localhost:8080",
            description="Address the tool uses to call Open WebUI's own API, from the backend's point of view (usually localhost and the container's internal port, not the public/Tailscale address).",
        )
        OPEN_WEBUI_API_KEY: str = Field(
            default="",
            description="Personal API key from Open WebUI (Settings -> Account -> API Keys), used for the image upload. Set it here in the valve, not in the code.",
        )
        MAX_WAIT_SECONDS: int = Field(default=300, description="Give up on a render after this long.")
        REQUEST_TIMEOUT_SECONDS: int = Field(default=15, description="Per-HTTP-request timeout.")
        MAX_BATCH_SIZE: int = Field(default=4, description="Upper bound on batch_size (VRAM guard).")
        ALLOW_UNLISTED_SERVERS: bool = Field(
            default=True,
            description="Let the model target any well-formed ComfyUI address, not just the ones in GPU_SERVERS. Turn off to restrict the tool to the list (stops a model from making the Open WebUI backend send render jobs to arbitrary hosts).",
        )
        SHOW_PROGRESS: bool = Field(
            default=True,
            description="Show live progress (stage names and sampler step/percent) in Open WebUI's status line, via ComfyUI's websocket. Falls back silently to plain polling if the websocket can't connect.",
        )
        IMAGE_DELIVERY: Literal["model_embed", "files_event", "message_event"] = Field(
            default="model_embed",
            description=(
                "How the finished image reaches the chat. "
                "'model_embed': the result includes image_markdown and the model is told to put it in its reply (what the SD1.5 tool effectively does). "
                "'files_event': the tool attaches the image to the message via an event (Open WebUI's built-in image generation mechanism); the model is told not to embed it. "
                "'message_event': the tool appends markdown to the message text via an event; this text can be overwritten when the model streams its reply."
            ),
        )
        LOG_JOBS: bool = Field(
            default=True,
            description="Keep a durable record of every completed render (full parameters, timestamp, filenames, seed, etc.) for later reference. Applies to completed renders only, not queue_only submissions.",
        )
        LOG_BACKEND: Literal["syslog", "file", "both"] = Field(
            default="both",
            description="'syslog' writes to the local syslog socket (journald picks it up as 'journalctl -t <SYSLOG_IDENT>' IF this process's /dev/log is the host's journald socket - not true by default in an unmodified Docker container). 'file' writes a rotating JSON-lines file at JOB_LOG_PATH. 'both' tries syslog and always keeps the file too, so a job is never lost if syslog isn't reachable.",
        )
        SYSLOG_ADDRESS: str = Field(
            default="/dev/log",
            description="Syslog socket path. In Docker, only reaches the host's journal if /dev/log is bind-mounted in; otherwise entries land in the container's own log stream instead.",
        )
        SYSLOG_IDENT: str = Field(
            default="comfy_sdxl_direct",
            description="Syslog program identifier to filter by, e.g. `journalctl -t comfy_sdxl_direct` or `docker logs <container> | grep comfy_sdxl_direct`.",
        )
        JOB_LOG_PATH: str = Field(
            default="/app/backend/data/comfy_outputs/job_log.jsonl",
            description="Rotating JSON-lines file of completed jobs (one job per line). Used when LOG_BACKEND is 'file' or 'both', and automatically as a fallback if the syslog socket can't be opened.",
        )
        JOB_LOG_MAX_BYTES: int = Field(default=5_000_000, description="Rotate the job log file after it reaches this size.")
        JOB_LOG_BACKUP_COUNT: int = Field(default=5, description="How many rotated job log files to keep.")
        LOG_TO_SQLITE: bool = Field(
            default=True,
            description="Record every job attempt into a queryable SQLite database (searchable via retrieve_image's search_jobs) - including rejected or timed-out jobs, not just completed renders. Independent of LOG_JOBS/LOG_BACKEND, which are the separate syslog/file log of completed renders only.",
        )
        JOB_DB_PATH: str = Field(
            default="/app/backend/data/comfy_outputs/comfy_jobs.sqlite3",
            description="SQLite database file for the job index. Defaults alongside JOB_LOG_PATH/OUTPUT_DIR - if that directory is already a mounted volume, this file appears there automatically, readable from the host. Shared with comfy_sdxl_graph.py's writes and comfy_sdxl_retrieve.py's search_jobs; keep all three set to the same path.",
        )

    def __init__(self):
        self.valves = self.Valves()
        self.citation = False

    async def generate_image(
        self,
        positive_prompt: str,
        negative_prompt: str,
        batch_size: int = 1,
        source_image: Optional[str] = None,
        source_server: Optional[str] = None,
        denoise: Optional[float] = None,
        seed: int = -1,
        steps: int = 25,
        cfg: float = 5.0,
        sampler_name: str = "dpmpp_2m",
        scheduler: str = "karras",
        width: int = 1216,
        height: int = 824,
        checkpoint_name: Optional[str] = None,
        loras: Optional[List[Dict[str, Any]]] = None,
        gpu_server: Optional[str] = None,
        return_img_url: bool = False,
        queue_only: bool = False,
        verbose: bool = False,
        __event_emitter__: Optional[Callable[[dict], Any]] = None,
    ) -> Dict[str, Any]:
        """
        Render an SDXL image on the ComfyUI server. Prompts are sent verbatim.
        Text-to-image by default; pass source_image to refine an image that was

        TOOLKIT: this is one of three related tools, all sharing the same GPU_SERVERS. Use
        generate_image for ordinary SDXL renders (txt2img/img2img, LoRAs). Use retrieve_image to
        fetch a finished result by job id or filename, check on a job queued with queue_only=true,
        or list a server's recent jobs when you don't have an id. Use run_workflow only when this
        fixed graph can't do what's needed - ControlNet, IP-Adapter, compositing, or any custom node
        graph. A result's 'server' value can be passed as another call's gpu_server, and an image's
        'use_as_source_image' can be passed as source_image, to chain across any of the three.
        already generated (multi-pass img2img).

        Every parameter below except positive_prompt/negative_prompt is optional and has a normal
        default. If your calling format requires a value for every parameter and won't let you
        omit one, pass "" for an unused text parameter, "{}" or "[]" for loras, or the number/
        boolean already shown as its default below - all are treated exactly like omitting it.

        :param positive_prompt: Positive prompt text, sent exactly as written.
        :param negative_prompt: Negative prompt text, sent exactly as written.
        :param batch_size: Number of images to generate in one run. Pass "" (or omit) for the default, 1.
        :param source_image: Pass "" (or omit) for normal text-to-image. To refine an earlier result, pass its 'use_as_source_image' value (and the same gpu_server). This switches to img2img; width/height are then taken from that image.
        :param source_server: Only needed when source_image lives on a DIFFERENT server than gpu_server (e.g. moving a multi-pass job to another GPU). Set it to the server the source image was rendered on (its earlier result's 'server' value); the tool copies the file across before rendering. Pass "" (or omit) when source_image is already on gpu_server.
        :param denoise: Sampler denoise, 0.0-1.0. Pass "" (or omit) for the default: 1.0 for text-to-image, 0.6 for img2img. Lower values stay closer to source_image (about 0.3-0.5 for light refinement).
        :param seed: Random seed. Pass "" (or omit), or -1, for a random one.
        :param steps: Sampler steps. Pass "" (or omit) for the default, 25.
        :param cfg: CFG scale. Pass "" (or omit) for the default, 5.0.
        :param sampler_name: KSampler sampler, e.g. dpmpp_2m, dpmpp_2m_sde, dpmpp_sde, euler, euler_ancestral, ddim, uni_pc. Pass "" (or omit) for the default, dpmpp_2m.
        :param scheduler: KSampler scheduler, e.g. karras, normal, simple, exponential, sgm_uniform, beta. Pass "" (or omit) for the default, karras.
        :param width: Image width in pixels (text-to-image only, snapped to a multiple of 8). Pass "" (or omit) for the default, 1216.
        :param height: Image height in pixels (text-to-image only, snapped to a multiple of 8). Pass "" (or omit) for the default, 824.
        :param checkpoint_name: Pass "" (or omit) to use the configured default checkpoint. Only set this to an exact checkpoint filename as listed on the server.
        :param loras: A list like [{"lora": "name.safetensors", "strength": 0.8}]. Pass "" (or omit), "{}", or "[]" for no LoRAs.
        :param gpu_server: Pass "" (or omit) to use the default server. Otherwise a configured server, or (if allowed) any ComfyUI address, full URL or bare IP.
        :param return_img_url: true to include download URLs for each image in the result: 'comfy_url' (direct link to the file on the GPU server) and 'chat_url' (the copy shown in the chat; an Open WebUI path when uploaded). false (the normal choice) keeps results small.
        :param queue_only: true to only submit the job and return immediately with its job id and queue position (or ComfyUI's error), without waiting for the render - use when the server's queue is long; the image is saved to the GPU server's output folder but is NOT delivered to the chat in this mode. false (the normal choice) waits for the actual result.
        :param verbose: true to also return the full submitted workflow and server history. false (the normal choice) otherwise.
        """
        v = self.valves

        async def status(text: str, done: bool = False):
            await _emit(__event_emitter__, {"type": "status", "data": {"description": text, "done": done}})

        # ---- validate & resolve arguments ---------------------------------
        try:
            allowed = list(dict.fromkeys(list(v.GPU_SERVERS) + [v.DEFAULT_GPU_SERVER]))
            server = resolve_server(gpu_server, v.DEFAULT_GPU_SERVER, allowed, v.ALLOW_UNLISTED_SERVERS)

            # Models often send ""/"default"/"null"/None for an optional arg they don't need -
            # including ones with a real (non-None) Python default, e.g. when a calling format's
            # own schema won't let the model omit a declared parameter at all. Restore each one's
            # real default before it's used, rather than letting a stray "" reach a numeric
            # comparison below (which would raise an unhandled TypeError, not a clean error).
            checkpoint_name = None if is_unset(checkpoint_name) else checkpoint_name.strip()
            source_image = None if is_unset(source_image) else source_image.strip()
            if is_unset(batch_size):
                batch_size = 1
            if is_unset(seed):
                seed = -1
            if is_unset(steps):
                steps = 25
            if is_unset(cfg):
                cfg = 5.0
            if is_unset(denoise):
                denoise = None
            if is_unset(sampler_name):
                sampler_name = "dpmpp_2m"
            if is_unset(scheduler):
                scheduler = "karras"
            if is_unset(width):
                width = 1216
            if is_unset(height):
                height = 824

            if isinstance(loras, str):  # some models send JSON as a string
                loras = json.loads(loras) if not is_unset(loras) else None
            # An actual empty dict/list (not a string) already behaves like "no LoRAs" below,
            # via `if loras:` here and `loras or None` where the workflow is built.

            if not 1 <= batch_size <= v.MAX_BATCH_SIZE:
                raise ValueError(f"batch_size must be between 1 and {v.MAX_BATCH_SIZE}.")
            if not 1 <= steps <= 150:
                raise ValueError("steps must be between 1 and 150.")
            if not 0.0 <= cfg <= 30.0:
                raise ValueError("cfg must be between 0 and 30.")

            is_img2img = bool(source_image)
            if denoise is None:
                denoise = DEFAULT_IMG2IMG_DENOISE if is_img2img else DEFAULT_TXT2IMG_DENOISE
            if not 0.0 <= denoise <= 1.0:
                raise ValueError("denoise must be between 0.0 and 1.0.")

            width = max(64, int(round(width / 8)) * 8)
            height = max(64, int(round(height / 8)) * 8)
            resolved_seed = seed if seed >= 0 else random.randint(0, 2**50)

            wanted_ckpt = checkpoint_name or v.DEFAULT_CHECKPOINT
            client = ComfyClient(server, v.REQUEST_TIMEOUT_SECONDS)
            available_ckpts = await asyncio.to_thread(client.list_checkpoints)
            ckpt = resolve_checkpoint(wanted_ckpt, available_ckpts) if available_ckpts else wanted_ckpt

            copied_from = None
            if is_img2img and not is_unset(source_server):
                resolved_source_server = resolve_server(source_server, server, allowed, v.ALLOW_UNLISTED_SERVERS)
                if resolved_source_server != server:
                    src_subfolder, src_filename = parse_source_image(source_image)
                    await status(f"Copying source image from {resolved_source_server}...")
                    await copy_source_image(
                        resolved_source_server, client, src_subfolder, src_filename, v.REQUEST_TIMEOUT_SECONDS
                    )
                    copied_from = resolved_source_server

            workflow = build_workflow(
                positive_prompt=positive_prompt,
                negative_prompt=negative_prompt,
                checkpoint_name=ckpt,
                seed=resolved_seed,
                steps=steps,
                cfg=cfg,
                sampler_name=sampler_name,
                scheduler=scheduler,
                denoise=denoise,
                width=width,
                height=height,
                batch_size=batch_size,
                source_image=source_image,
                loras=loras or None,
                filename_prefix=v.FILENAME_PREFIX,
            )

            job_uuid = str(uuid.uuid4()) if v.LOG_TO_SQLITE else None
            if job_uuid:
                input_json = {
                    "tool": "generate_image", "positive_prompt": positive_prompt, "negative_prompt": negative_prompt,
                    "batch_size": batch_size, "source_image": source_image, "source_server": source_server,
                    "denoise": denoise, "seed": seed, "steps": steps, "cfg": cfg, "sampler_name": sampler_name,
                    "scheduler": scheduler, "width": width, "height": height, "checkpoint_name": checkpoint_name,
                    "loras": loras, "gpu_server": gpu_server, "queue_only": queue_only,
                }
                await asyncio.to_thread(
                    record_job_built, v.JOB_DB_PATH, job_uuid, "generate_image", server,
                    input_json, workflow, positive_prompt, negative_prompt,
                )
        except (ValueError, TypeError, json.JSONDecodeError, ComfyError) as e:
            # TypeError is here as a backstop for a genuinely malformed (not just "skipped") value
            # slipping past the is_unset() normalization above - e.g. a non-numeric string for a
            # numeric argument - so it becomes a clean error instead of an unhandled crash.
            return {"success": False, "error": str(e)}

        # ---- queue only: submit, report, don't wait -------------------------
        if queue_only:
            try:
                await status("Submitting job to the queue...")
                info = await asyncio.to_thread(client.submit_prompt, workflow, str(uuid.uuid4()))
                ahead = await asyncio.to_thread(client.jobs_ahead, info.get("number"))
            except ComfyError as e:
                logger.error("Queue submission failed: %s", e)
                await status(f"Queue rejected the job: {e}", done=True)
                if job_uuid:
                    await asyncio.to_thread(record_job_failed, v.JOB_DB_PATH, job_uuid, "submit", str(e), e.body)
                rejected: Dict[str, Any] = {"success": False, "queued": False, "error": str(e), "server": server}
                if e.body:
                    rejected["server_response"] = e.body
                return rejected
            job_id = info["prompt_id"]
            if job_uuid:
                await asyncio.to_thread(record_job_submitted, v.JOB_DB_PATH, job_uuid, job_id, info)
            await status(f"Queued as job {job_id[:8]}", done=True)
            queued: Dict[str, Any] = {
                "success": True,
                "queued": True,
                "job_id": job_id,
                "queue_number": info.get("number"),
                "jobs_ahead": ahead,
                "server": server,
                "mode": "img2img" if is_img2img else "txt2img",
                "output_filename_prefix": v.FILENAME_PREFIX,
                "params": {
                    "positive_prompt": positive_prompt,
                    "negative_prompt": negative_prompt,
                    "seed": resolved_seed,
                    "steps": steps,
                    "cfg": cfg,
                    "sampler_name": sampler_name,
                    "scheduler": scheduler,
                    "denoise": denoise,
                    "batch_size": batch_size,
                    "checkpoint": ckpt,
                    "loras": loras or [],
                    **({"source_image": source_image} if is_img2img else {"width": width, "height": height}),
                },
                "note": (
                    "The GPU server accepted the job. It was not waited for and no image was delivered; "
                    "it will be saved in the server's output folder. jobs_ahead counts jobs queued before "
                    "this one, including any currently running."
                ),
            }
            if info.get("node_errors"):
                queued["node_errors"] = info["node_errors"]
            if ckpt != wanted_ckpt:
                queued["checkpoint_note"] = f"Requested checkpoint {wanted_ckpt!r} was resolved to {ckpt!r} on this server."
            if copied_from:
                queued["source_image_note"] = f"Copied source image from {copied_from} to {server} before queuing."
            if verbose:
                queued["workflow"] = workflow
            return queued

        # ---- run ----------------------------------------------------------
        render_completed = False
        try:
            await status("Rendering..." if not is_img2img else "Refining source image...")
            result = await client.run(
                workflow, v.MAX_WAIT_SECONDS, on_status=status, show_progress=v.SHOW_PROGRESS,
                job_uuid=job_uuid, db_path=v.JOB_DB_PATH if job_uuid else None,
            )
            render_completed = True  # the render itself succeeded; anything below is chat delivery

            images_out: List[Dict[str, Any]] = []
            chat_sources: List[str] = []
            warnings: List[str] = []
            for img in result["images"]:
                subfolder = img.get("subfolder", "")
                ref = f"{subfolder}/{img['filename']}" if subfolder else img["filename"]
                comfy_url = client.view_url(img)
                delivered_url, delivery = comfy_url, "direct_comfy_url"

                data: Optional[bytes] = None
                if v.UPLOAD_TO_OPEN_WEBUI or v.SAVE_LOCAL_COPY:
                    try:
                        data = await asyncio.to_thread(client.fetch_image, img)
                    except ComfyError as e:  # the render worked; don't fail the call over this
                        warnings.append(str(e))
                if data is not None and v.SAVE_LOCAL_COPY:
                    out_dir = Path(v.OUTPUT_DIR)
                    out_dir.mkdir(parents=True, exist_ok=True)
                    (out_dir / f"{result['prompt_id'][:8]}_{img['filename']}").write_bytes(data)
                if data is not None and v.UPLOAD_TO_OPEN_WEBUI:
                    path, err = await asyncio.to_thread(
                        upload_to_open_webui,
                        v.OPEN_WEBUI_BASE_URL,
                        v.OPEN_WEBUI_API_KEY,
                        data,
                        img["filename"],
                        v.REQUEST_TIMEOUT_SECONDS,
                    )
                    if path:
                        delivered_url, delivery = path, "openwebui_upload"
                    else:
                        logger.warning("Open WebUI upload failed: %s", err)
                        warnings.append(
                            f"Open WebUI upload failed ({err}); using a direct ComfyUI link, "
                            f"which only displays if the browser can reach {server}."
                        )

                chat_sources.append(delivered_url)
                entry: Dict[str, Any] = {
                    "filename": img["filename"],
                    "subfolder": subfolder,
                    "delivery": delivery,
                    "use_as_source_image": ref,
                }
                if return_img_url:
                    entry["comfy_url"] = comfy_url
                    entry["chat_url"] = delivered_url
                    # Ready-made clickable link (prefers the Open WebUI copy, which the browser can always reach).
                    entry["link_markdown"] = f"[{img['filename']}]({delivered_url})"
                images_out.append(entry)
            warnings = list(dict.fromkeys(warnings))

            # Event delivery needs an emitter; without one we fall back to the model embedding it.
            emitted = v.IMAGE_DELIVERY != "model_embed" and bool(__event_emitter__)
            if emitted:
                if v.IMAGE_DELIVERY == "files_event":
                    payload = {"type": "files", "data": {"files": [{"type": "image", "url": u} for u in chat_sources]}}
                else:
                    md = "\n\n".join(f"![generated image]({u})" for u in chat_sources)
                    payload = {"type": "message", "data": {"content": md + "\n\n"}}
                await _emit(__event_emitter__, payload)
            await status("Done", done=True)
        except ComfyError as e:
            logger.error("SDXL render failed: %s", e)
            await status(f"Render failed: {e}", done=True)
            # run() already recorded this failure into the job DB at the correct stage
            # (submit vs wait); nothing more to record here.
            msg = str(e)
            if client.lookup_error:
                msg += (
                    f" [Note: the checkpoint list could not be fetched from this server "
                    f"({client.lookup_error}), so the checkpoint name was sent unverified.]"
                )
            return {"success": False, "error": msg, "server": server}
        except Exception as e:  # keep the model from seeing a raw traceback
            logger.exception("Unexpected error during SDXL render")
            await status("Render failed", done=True)
            if job_uuid and not render_completed:
                await asyncio.to_thread(record_job_failed, v.JOB_DB_PATH, job_uuid, "wait", f"Unexpected error: {e}")
            return {"success": False, "error": f"Unexpected error: {e}", "server": server}

        out: Dict[str, Any] = {
            "success": True,
            "mode": "img2img" if is_img2img else "txt2img",
            "prompt_id": result["prompt_id"],
            "server": server,
            "images": images_out,
            "params": {
                "positive_prompt": positive_prompt,
                "negative_prompt": negative_prompt,
                "seed": resolved_seed,
                "steps": steps,
                "cfg": cfg,
                "sampler_name": sampler_name,
                "scheduler": scheduler,
                "denoise": denoise,
                "batch_size": batch_size,
                "checkpoint": ckpt,
                "loras": loras or [],
                **({"source_image": source_image} if is_img2img else {"width": width, "height": height}),
            },
            "displayed_via": v.IMAGE_DELIVERY if emitted or v.IMAGE_DELIVERY == "model_embed" else "none",
            "note": (
                "Images are already displayed to the user; don't embed them again. "
                if emitted
                else "Include image_markdown exactly as given in your reply so the user can see the image. "
            )
            + "For another pass, call again with source_image=<use_as_source_image> and gpu_server="
            + server
            + ".",
        }
        if return_img_url:
            out["note"] += (
                " To show a link to the user, paste link_markdown exactly as given so it renders as a "
                "clickable link; don't put URLs in backticks or code blocks."
            )
        if warnings:
            out["warnings"] = warnings
        if ckpt != wanted_ckpt:
            out["checkpoint_note"] = f"Requested checkpoint {wanted_ckpt!r} was resolved to {ckpt!r} on this server."
        if copied_from:
            out["source_image_note"] = f"Copied source image from {copied_from} to {server} before rendering."
        if not emitted:
            out["image_markdown"] = "\n\n".join(f"![generated image]({u})" for u in chat_sources)
        if verbose:
            out["workflow"] = workflow
            out["history"] = result["history"]

        log_completed_job(
            v,
            {
                "event": "render_complete",
                "job_id": result["prompt_id"],
                "server": server,
                "mode": out["mode"],
                "filenames": [img["filename"] for img in images_out],
                "params": out["params"],
                **({"copied_source_image_from": copied_from} if copied_from else {}),
            },
        )
        return out
